### PR TITLE
Release/judas priest

### LINKED ISSUE #4212: Sign in key panel being stretched
The sign in key panel is being stretched: 

Screenshot 2023-09-12 at 14 47 19

Noticed by @mica000 here: https://github.com/leather-wallet/extension/pull/4210#issuecomment-1715585760

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out this version of the Leather — download [extension builds](https://github.com/leather-wallet/extension/actions/runs/6161341038).

Contents: 

- https://github.com/leather-wallet/extension/issues/4212
- https://github.com/leather-wallet/extension/issues/4185
- https://github.com/leather-wallet/extension/issues/4162
- https://github.com/leather-wallet/extension/issues/4151
- https://github.com/leather-wallet/extension/issues/4195
- https://github.com/leather-wallet/extension/issues/4187
- https://github.com/leather-wallet/extension/issues/3710

### CODE REVIEW

**Review by kyranjamie — DISMISSED** [review]
👍🏼 

remember to merge, not rebase

**Comment by pete-watters** [comment]
> 👍🏼
> 
> remember to merge, not rebase

I took in Anas's fix for BG colour so I need to re-review please

**Comment by mica000** [comment]
@pete-watters this is being stretched 
SCR-20230912-mbkv

**Comment by pete-watters** [comment]
> @pete-watters this is being stretched SCR-20230912-mbkv

Thanks, I'll fix it https://github.com/leather-wallet/extension/issues/4212

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
