### PR TITLE
fix: negative stx available balance

### LINKED ISSUE #3761: Don't subtract fee from balance for incoming Stacks transactions
To reproduce:
1. Send STX transaction with 0.0025 STX fee to a fresh address
2. Look at the balance when activity is pending:

image

### PR DESCRIPTION
**Pull request by alter-eggo**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5389139293).

Closes #3761 and #3716

Fixes the issue of extracting fees of inbound txs from available balance

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]
Can you describe the changes?

Wonder also if a `Math.min(0, ...balanceValue)` (or bignumber equivalent might be desired here)?

**Comment by alter-eggo** [comment]
@kyranjamie you mean `Math.max`? to remove possibility of showing negative value?

**Comment by alter-eggo** [comment]
@kyranjamie I changed according to your suggestion but then revert. I think we shouldn't manually set negative value to zero, as this indicates about problems in code. if we did this before - this bug would probably be always there

**Comment by kyranjamie** [comment]
Yep, makes sense

**Review by fbwoolf — APPROVED** [review]

**Pull request merged**
