### PR TITLE
fix: slower render performance on create account list

### LINKED ISSUE #2139: Improve performance of accounts list when connecting to dApp
Similar to the performance gains needed in #2078 for the _Switch account_ modal. The list that appears with all accounts when connecting to a dApp also needs to be improved. Currently, with hundreds of accounts, the list eats all browser memory and grinds to a halt.

image

The wallet loads _all_ the accounts a user has in the UI. We should likely take a similar approach to the aforementioned PR, and ensure only in-view components are rendered.

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1774421713).

Fixes #2139

Not to be merged until @fbwoolf's onboarding changes. Fixes issue with the choose account's list performance. Also simplifies some of the container CSS.

Note, this PR removes the scrollbar in popup mode, which is a fairly common pattern for browser extensions (metamask, coinbase wallet do it, too). The problem is that if a scrollbar auto/appears hides, either the content or the size of the window must adjust, which is jarring, or you always enable it, and it doesn't look good when it doesn't need to scroll. Having been playing around with this, it feels way better without.

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]
Looks good! Will rebase this on my changes once they get merged. 👍

**Comment by kyranjamie** [comment]
Had a quick look at this. The onboarding steps still need centreing. Can come back to this but rn still finishing my other PR.

Did you mean to remove the OnboardingContainer? Only the onboarding pages are centred, so the thinking is that we should centre where needed explicitly, rather than setting global styles so that everything is centered.

**Comment by fbwoolf** [comment]
> Had a quick look at this. The onboarding steps still need centreing. Can come back to this but rn still finishing my other PR.
> 
> Did you mean to remove the OnboardingContainer? Only the onboarding pages are centred, so the thinking is that we should centre where needed explicitly, rather than setting global styles so that everything is centered.

I thought I was taking this over ...in the middle of it still. You wanting to take it back? I only removed the `OnboardingContainer` to make rebasing my changes easier, then was going to look at adding it back. Let me know if you are wanting me to finish this?

**Review by fbwoolf — APPROVED** [review]
Going to merge this into dev bc I need these changes to make more onboarding updates off the dev branch.

**Comment by fbwoolf** [comment]
Nvm, the integration tests are failing on the account list changes. @kyranjamie hoping you can look at on Monday before we merge it.

**Comment by fbwoolf** [comment]
I based my new updates to onboarding on this branch: https://github.com/hirosystems/stacks-wallet-web/pull/2182

**Pull request merged**
