### PR TITLE
chore: upgrade stacks wallet-sdk to 3.4.0

### LINKED ISSUE #2282: Address changes to stacks.js packages
https://discord.com/channels/621759717756370964/803293319328170024/948604001174323241

as of stacks.js >3.3.0 the bundling (main fields) is a bit different, for the same behavior as previously you will likely want to add a resolve.alias to the webpack config as seen here: https://github.com/janniks/stacks-wallet-web/blob/fea34ecfa667518ea9eecdf3b8161aa8e3fad1e3/webpack/webpack.config.base.js#L72-L82 (only for the relevant updated packages)

another diff for when upgrading all stacks.js packages to latest: https://github.com/hirosystems/stacks-wallet-web/compare/dev...janniks:add-esm-alias

### LINKED ISSUE #2283: Upgrade to latest `@stacks/wallet-sdk`
We need to upgrade the wallet-sdk to the version including @friedger's PR https://github.com/hirosystems/stacks.js/pull/1204

This will fix profile signing for new users

cc/ @markmhx @pradel

### PR DESCRIPTION
**Pull request by beguene**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2051795788).

Original PR https://github.com/hirosystems/stacks-wallet-web/pull/2289
Fixes https://github.com/hirosystems/stacks-wallet-web/issues/2283
and https://github.com/hirosystems/stacks-wallet-web/issues/2282

This is required to merge https://github.com/hirosystems/stacks-wallet-web/pull/2310

@fbwoolf @kyranjamie @He1DAr

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Comment by markmhendrickson** [comment]
@kyranjamie will review this PR then we'll move it to QA at which point we'll do a full regression test before releasing.

@pradel given a few other fires we're putting out at the moment, it's likely this won't all be completed until next week.

**Comment by pradel** [comment]
Okay, thanks for the update

**Review by kyranjamie — APPROVED** [review]

**Comment by markmhendrickson** [comment]
We will begin QA'ing this week

**Comment by markmhendrickson** [comment]
QA for this PR is awaiting inclusion of https://github.com/hirosystems/stacks.js/pull/1230 in the underlying test app since we ran into problems since resolved by it during previous testing

**Comment by markmhendrickson** [comment]
@beguene has this PR been merged and released already?

**Comment by beguene** [comment]
@markmhx This is obsolete (and solved) now since we just merged this PR.
https://github.com/hirosystems/stacks-wallet-web/pull/2333

**Pull request closed without merging**
