### PR TITLE
Refactor/move crypto functions

### LINKED ISSUE #1207: Refactor messaging
Refactor/rename messaging folders, files, and code to better coordinate and understand message flow.

Note: There is a related issue for creating a `Manifest` folder with separate manifests for each browser type.
https://github.com/blockstack/stacks-wallet-web/issues/1206

Questions/concerns:
1. `App` seems misused in our naming, or at least it is unclear.
2. Why do we sometimes use the `backgroundPort` and other times not?

Tasks:
- [x] Remove `extension` folder and restructure so we clearly define context of the script (`scripts` folder)
- [x] Rename `message-bus` to `content-script`
- [x] Remove `Background` folder and rename `index` to `background`
- [x] Relocate `popup.ts` to scripts folder
- [x] Refactor `message-types` to clearly define what message type goes with which context
   - [x] Separate `Methods` into `InternalMethods` and `ExternalMethods`
   - [x] Remove unused `walletResponse` from methods
   - [x] Rename `walletRequest` to something more inline with the other internal methods for the vault, `getWallet`?
   - [x] Rename `MessageFromApp` to `VaultActions` (bc the vault is setup like a reducer)

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Stacks Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/882221013).

Addresses some renaming/organising of the code that @fbwoolf and I thought will make messaging easier to understand.

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]
Nice refactor!

**Comment by aulneau** [comment]
@kyranjamie @fbwoolf This looks good from my perspective, at least the naming updates and organization around messaging, however I don't feel as though the folder restructuring makes sense.

Previously we had a folder called "extension" which kept all web-extension based code in its own folder, but now we have it in the root of the app.

Screen Shot 2021-05-27 at 8 17 26 AM

To me, this is confusing because it blurs the line between the extension code and the react application code. I'd love for that to be clearer.

**Comment by fbwoolf** [comment]
> @kyranjamie @fbwoolf This looks good from my perspective, at least the naming updates and organization around messaging, however I don't feel as though the folder restructuring makes sense.
> 
> Previously we had a folder called "extension" which kept all web-extension based code in its own folder, but now we have it in the root of the app.
> 
> Screen Shot 2021-05-27 at 8 17 26 AM
> 
> To me, this is confusing because it blurs the line between the extension code and the react application code. I'd love for that to be clearer.

@aulneau  I think we were going to move the React code into an `app` folder? I just didn't do that with this PR, but I can today before we merge this?

Nvm, I see it was merged!

**Comment by fbwoolf** [comment]
I can make do the `app` refactor today, let me know.

**Pull request merged**
