### PR TITLE
feat: make address clickable to copy

### PR DESCRIPTION
**Pull request by alter-eggo**
Small ux improvement:
It is always a pain for user to hover cursor over small icons. This pr allows user to copy address by clicking both on address and icon on home page

Screenshot (cursor is not shown here, as it hides when you make screenshot):
Screenshot 2023-02-16 at 23 29 58

### CODE REVIEW

**Comment by kyranjamie** [comment]
This is a nice UX improvement, thanks @alter-eggo.

While we're here, I wonder if we can _addres_ the following:

- Fixing the spelling mistake in address
- Making the interactive element a button (it wasn't before either)
  - This can be done with the `as="button"`, then the cursor prop isn't needed
- Fixing visual alignment of the icon (to me it looks 1 or 2px too high) cc @mica000

**Comment by alter-eggo** [comment]
@kyranjamie fixed spelling and ui
Screenshot 2023-02-17 at 18 27 50

**Comment by mica000** [comment]
Thanks, @alter-eggo!

We are currently also working on the header on this ticket and the changes in there would affect the changes above:

https://github.com/hirosystems/stacks-wallet-web/issues/3132#issuecomment-1433124048

Do you mind checking to see if it would help your case?

**Comment by alter-eggo** [comment]
@mica000 thanks! is seems this section should be completely reworked to meet design requirements. 
I think it's probably better to merge/close current pr as is, and do #3132 in separate pr

**Comment by mica000** [comment]
@alter-eggo Nice then! Seems good to go for me too :)

**Review by mica000 — APPROVED** [review]

**Comment by alter-eggo** [comment]
merged dev. with BTC address it looks like this:
Screenshot 2023-02-18 at 23 05 41

**Comment by fbwoolf** [comment]
Thanks again @alter-eggo, I'll get this one merged today.

**Comment by fbwoolf** [comment]
Closing bc commits being merged here: https://github.com/hirosystems/stacks-wallet-web/pull/3203

**Pull request closed without merging**
