### PR TITLE
fix(connect): remove unused post conditions

### PR DESCRIPTION
**Pull request by friedger**
This PR
* removes unused post conditions for stx transfer and contract deploy transactions

### CODE REVIEW

**Comment by hstove** [comment]
@friedger why do you consider these "unused"? There are valid reasons to pass a post condition, especially to a deploy transaction. A contract deploy can mint, transfer, etc.

**Comment by friedger** [comment]
@hstove post conditions are only checked on contract call and contract deploy: https://github.com/blockstack/stacks-blockchain/blob/6b405bfc3cc8dad13a69f7324518f61ef9c540c0/src/chainstate/stacks/db/transactions.rs#L543

**Comment by friedger** [comment]
Only the stx transfer is not necessary.

**Comment by hstove** [comment]
We've removed the transfer conditions in #574

**Pull request closed without merging**
