### PR TITLE
refactor: rename leaf to leather

### PR DESCRIPTION
**Pull request by alter-eggo**
See title

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]
LGTM

On name, would it be nice to name `leather-ui` or something?

**Comment by alter-eggo** [comment]
@kyranjamie leather-styles to leather-ui-styles? doesn't `styles` implies `ui`?

**Comment by kyranjamie** [comment]
It does, I just wonder if `leather-ui` is a better name

**Comment by alter-eggo** [comment]
seems styles is better 😁
Screenshot 2023-09-01 at 12 06 21

**Pull request merged**
