### PR TITLE
Update `@stacks/wallet-sdk@3.1.1`, fix bns `lookupProfile`

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1778933807).

Pushing @pradel's https://github.com/hirosystems/stacks-wallet-web/pull/2087 PR again so our CI/test builds run.

This PR will fixs the bns `lookupProfile` functionality. @pradel will write up steps we need to follow to QA this. cc/ @andresgalante can you plan when we'll include this in release?

### CODE REVIEW

**Comment by friedger** [comment]
There is a bug in 3.1.0 https://github.com/blockstack/stacks.js/pull/1152

**Comment by kyranjamie** [comment]
Thanks @friedger, yes this one is def not to merge yet. Converted to draft.

**Comment by pradel** [comment]
@kyranjamie would it be possible to get a new build with 3.1.1 please 🙏 ?

**Comment by kyranjamie** [comment]
@pradel done, building now

**Comment by pradel** [comment]
Amazing thanks!

**Comment by pradel** [comment]
Hey there, any update to merge this one? :)

**Comment by pradel** [comment]
The changes introduced in this pr are mostly related to how the profile is signed, so I think you need to login to an app using the publish_data scope. You could probably use the TODO app on this branch https://github.com/hirosystems/todos/pull/104.

You would have to log in using an account owning a .btc name and you can try to call the `lookupProfile` function that would fail with the current Hiro wallet version and work with the one built on this branch.

**Comment by andresgalante** [comment]
@kyranjamie I'd like to include this on our next release if possible. 

I'll move it to "QA" so @Eshwari007 or @timstackblock can pick it up while it's being reviewed.

**Review by fbwoolf — APPROVED** [review]

**Comment by Eshwari007** [comment]
@kyranjamie any input on how to test the ticket is much appreciated.Thx in ad

**Comment by andresgalante** [comment]
@Eshwari007 this is how to test it https://github.com/hirosystems/stacks-wallet-web/pull/2089#issuecomment-1024048391

**Comment by Eshwari007** [comment]
@kyranjamie Want to run by you if am missing something here.

- I created a todos' using a test btc name under :  https://todos-lovat.vercel.app/todos/
- I tried looking up for my btc name todos https://todos-lovat.vercel.app/todos/hiromaintest.btc
- Receiving the below:

Screen Shot 2022-01-31 at 4 09 59 PM

Used the link from https://github.com/hirosystems/todos/issues/103

**Comment by andresgalante** [comment]
Hi @pradel, would you be able to help Esh test this PR? if async on the ticket is too slow, we can try on Discord

**Comment by pradel** [comment]
@andresgalante happy to help, do you have a channel on discord for this?

**Comment by pradel** [comment]
I uploaded a build from the Todo app [pending pr](https://github.com/hirosystems/todos/pull/104) to netlify for you to test more easily https://blissful-agnesi-f97d5f.netlify.app/.

Now we just need https://github.com/hirosystems/stacks-wallet-web/pull/2194 to be merged into this branch and get a new build for the wallet in order to finish the testing part :)

Edit: The netlify build is not working so I prepared you a Sigle branch in order to test https://sigle-1ljk1nxmn-sigle.vercel.app/login

**Comment by Eshwari007** [comment]
> I uploaded a build from the Todo app [pending pr](https://github.com/hirosystems/todos/pull/104) to netlify for you to test more easily https://blissful-agnesi-f97d5f.netlify.app/.
> 
> Now we just need #2194 to be merged into this branch and get a new build for the wallet in order to finish the testing part :)
get a new build for the wallet in order to finish the testing part

cc @andresgalante @kyranjamie

**Comment by pradel** [comment]
## Testing flow

Demo link: https://sigle-9i6eqj7dj-sigle.vercel.app/login

These are the tests cases with the new Hiro wallet version:

1. legacy account migration: use an old account 12 word key with a `*.id.blockstack` attached to it and login. You should be able to see your existing drafts, published posts, visiting my blog as a public visitor should work too.
2. legacy account migration: use an old account 12 word key with a `*.id.stx` attached to it and login. You should be able to see your existing drafts, published posts, visiting my blog as a public visitor should work too.
3. account with `*.btc` domain: login with an account owning a .btc domain. You should see the .btc username in the left side menu (back part). Create a draft, publish it and then visit your public blog should work.
4. registering new account: create a new account without username linked to it and register a new username. You should see the .id.stx username in the left side menu (back part). Create a draft, publish it and then visit your public blog should work.

To view your public blog, on the top right corner of the dashboard click on this button 👇 
Screenshot 2022-02-02 at 17 14 48

**Comment by Eshwari007** [comment]
> https://sigle-9i6eqj7dj-sigle.vercel.app/login

@leopradel Somewhat good news.

**Use case 3** : I was able to login in with .btc address ( bns address visible on the left-hand corner as well), create a blog ,save and publish it. I tried selecting 'view my blog but received 'token issuer error 'https://sigle-9i6eqj7dj-sigle.vercel.app/hiromaintest.btc.  However, in the sigle app itself, I was able to view my test blog under the `Published`  and `Draft` section. 

**User case 4**: I tried login with a new account without username and received the following error on console
Screen Shot 2022-02-02 at 10 30 04 PM


Note: I dont have an account with bns name as per use case 1 and 2 hence will create one and test the app as well

**Comment by pradel** [comment]
Thanks for trying it out!

**For case 3**: the fact that you are seeing the "token issuer error" means that the profile is not signed properly, also meaning that the test failed.
Calling the API https://stacks-node-api.mainnet.stacks.co/v1/names/hiromaintest.btc show that your username is linked to the address `SP17YZQB1228EK9MPHQXA8GC4G3HVWZ66X7VRPMAX`. However your [profile](https://gaia.blockstack.org/hub/1FU7PS5jfAaKVg9YnYEBQZ9pndFM4kV6Uh/profile.json) public key is `0217ecac7614a7a724f0addfc4241f756129171cc460eef430e895f04a08ff5658`, and getting the address is actually not matching the one owned by the name. 
```js
const { getAddressFromPublicKey } = require('@stacks/transactions');
console.log(getAddressFromPublicKey('0217ecac7614a7a724f0addfc4241f756129171cc460eef430e895f04a08ff5658'));
// => SP2FB4MP6QZ1JV8JJZTCBYP7P9T6GXB0842YHYVX3
```
This is the result you would get by logging in with the current Hiro wallet version (without the fix from this pull request) as the profile is signed using the old stacks key. Can I ask you to triple check that the extension you tried does have the changes made in this pull request? https://github.com/hirosystems/stacks-wallet-web/pull/2196 

**For case 4**: it's fine as it's not related to this pull request and the Hiro wallet in general but rather the subdomain registrar (I created an issue in the repo already).

**Comment by Eshwari007** [comment]
@pradel Spoke too soon.
I logged out and retested the entire scenario (this time with both .stx and .btc)with #2196


**Findings:**

Use case 3: the irony is that this partially worked bfr the token error was produced but now with the fix branch am not able to see any actions on the app upon selecting the account with btc on it

https://user-images.githubusercontent.com/38872890/152385562-a3be0fa9-9aab-49fe-83d3-ac4ce185f43e.mov


Use case 4:I was able to sign in with an account that doesn't have a bns attached to it and it created name.stx for me in the app
Screen Shot 2022-02-03 at 11 23 16 AM

**Comment by kyranjamie** [comment]
When QA approved, I'll make these changes #2172 (rather than merging this PR), as it'll be a real pain to rebase on.

**Comment by pradel** [comment]
@Eshwari007  I did the testing on multiple devices and it worked all the time. Would you mind trying one more time with a clean cache? 🙏

**Comment by Eshwari007** [comment]
> @Eshwari007 I did the testing on multiple devices and it worked all the time. Would you mind trying one more time with a clean cache? 🙏

@pradel Yay-good news. Test passed -used #2172 
All the use cases passed. cc @kyranjamie

**Comment by andresgalante** [comment]
Thanks a lot @Eshwari007 for testing this PR. Lets get it into the next release after 3.1

**Pull request merged**
