### PR TITLE
feat: use window.location for ios redirect

### PR DESCRIPTION
**Pull request by hstove**
Helping @yknl get iOS setup

### CODE REVIEW

**Comment by yknl** [comment]
Can we also add `client=android` in case the problem exists also for the Android SDK? cc @friedger

**Comment by hstove** [comment]
No problem - I just updated to do that as well.

**Comment by yknl** [comment]
Thanks! 👍

**Comment by hstove** [comment]
@yknl have you tested it out to make sure it works?

**Comment by yknl** [comment]
Yes confirmed working on iOS.

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
