### PR TITLE
Release/sip10 ledger fix

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/6796028084).

@314159265359879 to QA and give approval for release

### CODE REVIEW

**Comment by 314159265359879** [comment]
4482 fixed!
When I use "send max" with the FARA BRC20 token it adds way to many digits. Max should be 950. @fbwoolf Is there any relation to these digits and the amount of decimals defined in the FARA token deployment? 

image

fix for 4491 looks good. Checking the rest now.

**Comment by 314159265359879** [comment]
4166, I am not sure if icon alignment with errors is fixed. Should it be horizontally centered with the text, it doesn't look like it is?

image

image

**Review by 314159265359879 — APPROVED** [review]
Please see questions above, I think this alright for release because it fixes the Ledger P1. I am not sure if you want to hold it until you also have a fix for the "max send" issue for BRC-20.

**Comment by kyranjamie** [comment]
I think these issues can be resolved in a follow up release so will merge

**Comment by pete-watters** [comment]
> 4166, I am not sure if icon alignment with errors is fixed. Should it be horizontally centered with the text, it doesn't look like it is?
> 
> image
> 
> image

I checked this on `dev` and they seem aligned to me? 
Screenshot 2023-11-08 at 11 43 11
Screenshot 2023-11-08 at 11 22 58

Screenshot 2023-11-08 at 11 44 37

If you are seeing something else, please re-open https://github.com/leather-wallet/extension/issues/4166 with some more details and I can fix it

**Pull request merged**
