### PR TITLE
fix: asset list formatted balance, closes #5452

### LINKED ISSUE #5452: Regression in Runes formatting
I'm seeing some slight regression with Runes formatting after the latest update. It's great that they are back, but they are no longer showing their symbol next to the amount. When you roll over to see the actual number, it's also not taking decimals into account so displaying as a bigger whole number than it actually is.

image

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out Leather build 3c91b23 — [Extension build](https://github.com/leather-wallet/extension/actions/runs/9239352881), [Test report](https://leather-wallet.github.io/playwright-reports/fix/runes-balance-formatting), [Storybook](https://fix-runes-balance-formatting--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=fix/runes-balance-formatting)

This PR should fix the formatted balance in the shared asset list item. This also includes the query pkg update that installs the Runes balance fix into the extension again. See: https://github.com/leather-wallet/mono/pull/155

Screenshot 2024-05-25 at 9 42 06 AM

Screenshot 2024-05-25 at 9 42 24 AM

Screenshot 2024-05-25 at 9 43 52 AM

## Summary by CodeRabbit

- **New Features**
  - Added memoization for generating `accountSlug` in account selection for improved performance.

- **Updates**
  - Renamed `balance` to `availableBalance` across various components for consistency.
  - Updated balance display logic to ensure accurate and clear representation.

- **Bug Fixes**
  - Improved element locators in tests for more reliable test execution.

- **Refactor**
  - Swapped order of properties in balance formatting to enhance readability.

- **Tests**
  - Updated element locators in profile and transaction tests for better accuracy.

### CODE REVIEW

**Comment by fbwoolf** [comment]
cc @brandonmarshall-tm can you confirm fixed here for you?

**Review by pete-watters — APPROVED** [review]
👍 code LGTM and I can see the tooltip balance formatted correctly. 

Brandon mentions the symbols not showing up in his issue and I still can't see them now

**Comment by fbwoolf** [comment]
> 
> Brandon mentions the symbols not showing up in his issue and I still can't see them now

Thx for pointing out the symbol, will fix before merging.

**Comment by brandonmarshall-tm** [comment]
Confirming that the formatting on rollover is fixed! But yes to Pete's point the symbol to the right of the balance is still missing. Like in this example 

image

**Comment by fbwoolf** [comment]
Symbol back @brandonmarshall-tm, thx @pete-watters...

Screenshot 2024-05-25 at 11 34 23 AM

**Comment by fbwoolf** [comment]
@alter-eggo I made some changes here to help get the tests using the test app working, might be relevant to the test reliability issue you are looking into? Not sure if my changes will consistently help them pass, but got me unstuck today ...they were failing all day until I made these changes.

**Pull request merged**
