### PR TITLE
Replace blockstack with @stacks libs

### PR DESCRIPTION
**Pull request by friedger**
##  Description

As a developer, I don't want to replace blockstack.js with stacks.js to later learn that I need blockstack.js for @stacks/connect.

This PR
* replaces imports of `blockstack` with the corresponding libs of stacks.js
* removes keychain package

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] API reference/documentation update
- [x] Other

## Does this introduce a breaking change?
Developers can remove blockstack as a peer deps from their apps.

## Are documentation updates required?
No

## Checklist
- [x] Tag 1 of @hstove or @kyranjamie or @aulneau for review

### CODE REVIEW

**Comment by markmhendrickson** [comment]
@friedger we plan to review, smoke test and release this during the newly initiated sprint.

**Comment by hstove** [comment]
Thanks Friedger, sorry for the delay - I will be working to merge this into the Connect 2.0 work

**Comment by markmhendrickson** [comment]
@hstove I'm moving this back to "in development" and assigning you so you can treat it like an issue for incorporating the same changes in the 2.0 work

**Comment by friedger** [comment]
I'll start a new PR for the current `master`

**Comment by friedger** [comment]
replaced by #743

**Pull request closed without merging**
