### PR TITLE
Release: `release/faulty-chimpanzee`

### PR DESCRIPTION
**Pull request by pete-watters**
This release contains: 
- https://github.com/leather-io/issues/issues/114
- https://github.com/leather-io/extension/issues/5252
- https://github.com/leather-io/issues/issues/104
- https://github.com/leather-io/extension/issues/5449
- https://github.com/leather-io/extension/issues/5374
- https://github.com/leather-io/extension/issues/5469
- https://github.com/leather-io/extension/issues/5470
- https://github.com/leather-io/extension/pull/5545
- https://github.com/leather-io/extension/pull/5564
- https://github.com/leather-io/extension/issues/5574
- https://github.com/leather-io/extension/pull/5588
- https://github.com/leather-io/issues/issues/102
- https://github.com/leather-io/issues/issues/108
- https://github.com/leather-io/extension/issues/4971
- https://github.com/leather-io/extension/issues/5548
- https://github.com/leather-io/extension/issues/5589

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Comment by pete-watters** [comment]
I have updated the release to include:
- https://github.com/leather-io/extension/issues/5589
- https://github.com/leather-io/extension/issues/5548

@fbwoolf can you please help verify that https://github.com/leather-io/extension/issues/5548 is now fixed?

@alter-eggo @edgarkhanzadian can you please help check everything looks OK?

**Comment by fbwoolf** [comment]
@pete-watters any understanding as to why the build links aren't in the description?

**Comment by fbwoolf** [comment]
Build to test here: https://github.com/leather-io/extension/actions/runs/9762463952

**Comment by fbwoolf** [comment]
> @fbwoolf can you please help verify that #5548 is now fixed?
> 
Retested here and is fixed.

**Comment by pete-watters** [comment]
> @pete-watters any understanding as to why the build links aren't in the description?

No I'm not sure at all. I haven't seen them on any PR's lately. Maybe its something to do with coderabbit?

**Pull request merged**
