### PR TITLE
release: nostalgic skunk

### LINKED ISSUE #5124: Fix delete icon alignment for network
Screenshot 2024-03-26 at 11 39 04

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build 051b1b5 — [Extension build](https://github.com/leather-io/extension/actions/runs/10288775339), [Test report](https://leather-io.github.io/playwright-reports/release-nostalgic-skunk), [Storybook](https://release-nostalgic-skunk--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=release-nostalgic-skunk)

This release contains:
- https://github.com/leather-io/issues/issues/215
- https://github.com/leather-io/extension/issues/4370

Along with:
- [feat(analytics): background analytics event](https://github.com/leather-io/extension/pull/5726/commits/967f7b1e0e2c3744fadd6a47983ad8d695585e91)
- [chore: force resolution of fast-xml-parser](https://github.com/leather-io/extension/pull/5726/commits/bbded0279fa9da87c76180ba264890cc06cdb8c8)
- [chore: update react-virtuoso package](https://github.com/leather-io/extension/pull/5726/commits/c874c00e80d71f25730230502eb12a3370846e12)
- [fix: mainnet faker contract address](https://github.com/leather-io/extension/pull/5726/commits/17d71a80134deceb5e5d30ce8ff84e027fd807df)
- https://github.com/leather-io/extension/issues/5124
- https://github.com/leather-io/extension/issues/4972

@alter-eggo has more work to add to this but I'm opening this early as there have been some big code refactors done so it's worth a detailed pre-release test by @markmhendrickson + @314159265359879

### CODE REVIEW

**Comment by 314159265359879** [comment]
for the next couple of days I will run this version to check it out. So far so good.

**Comment by 314159265359879** [comment]
Leather logo in extension popup is gone. 
image

Looks alright in tab (maximized)
image

**Comment by markmhendrickson** [comment]
Let's include https://github.com/leather-io/extension/pull/5690 as well for holistic testing and release? cc @alter-eggo

**Comment by markmhendrickson** [comment]
@314159265359879 @DeeList can you two review various API-based flows as well to verify that headers show up as expected?

**Comment by 314159265359879** [comment]
I am not sure what this is about:
image

Tested sending assets on stacks and bitcoin. minting and listing, looks good. 
I see the Leather title showing normally now.

**Review by 314159265359879 — APPROVED** [review]
I am not sure if the screenshot I added (that pops up when the wallet is being set up) requires immediate attention. It didn't block me on anything.

**Comment by markmhendrickson** [comment]
See issue with sending BRC-20 tokens from @DeeList [here](https://trustmachines.slack.com/archives/C0520G8J33M/p1723020350959789?thread_ts=1722234630.097039&cid=C0520G8J33M)

**Comment by 314159265359879** [comment]
Deelist mentioned that BRC20 looked broken. But I do not see that issue he described. Going through the BRC20 send flow, I can transmit the transaction to create the transfer inscription. There is a small issue with the title here (visual) on the confirm page:
image

I also tested the send flow for the transfer inscription. Looking good too. 
image

I tested this build: release/nostalgic-skunk#ac21ff8


I do notice that sending the payment for the BRC transfer through the ordinalsbot integration shows first but it doesn't show the rest of the steps after the payment has been completed. An hour after confirmation no transfer inscription has been made. Have their been any updates to this service? (this is shown, nothing after that:)
image

**Comment by markmhendrickson** [comment]
The app menu now appears during the wallet creation and restoration flows (which is a good enhancement) though it also contains both "Switch account" and "Sign out" options, which should be hidden if the user hasn't yet configured / added a wallet.

image

Trying these options anyway results in these two error view variants:

image

image

We should fix these error views (in addition to preventing their access, by removing the two options from the menu). The latter variant should be consistently used, and its styles should be fixed (e.g. it shouldn't be left-aligned and squished up against the viewport like that without app nav up top).

In sum, these are the needs:

1. [ ] Hide "Switch account" and "Sign out" options from menu when no wallet configured
2. [ ] Create integration test per related [acceptance criterion](https://www.notion.so/trustmachines/Given-user-has-no-wallet-configured-when-opening-app-menu-then-user-sees-no-options-for-Switch-ac-280d5fda1f4b4d2ea7e2ec51db14fd25?pvs=4)
3. [ ] Fix ["Error"](https://www.notion.so/trustmachines/Error-b3834e0708a9463b9bce85a4174a6710?pvs=4) view styles
5. [ ] Create visual regression test for above item
4. [ ] Ensure error view is applied when triggering error from ["View Secret Key"](https://www.notion.so/trustmachines/View-Secret-Key-cabb13c4284043bc9a986ae5b52e2370?pvs=4) view
5. [ ] Create integration test per related [acceptance criterion](https://www.notion.so/trustmachines/Given-user-is-viewing-when-triggering-error-then-user-views-93a1fad3e23d4a139af19beac9186265?pvs=4)

**Comment by markmhendrickson** [comment]
I found [this issue](https://github.com/leather-io/extension/issues/5734) with the dismissal option for the hardware wallet connection view while testing this build, but it's also present in the production build. I'm flagging here in any case, in case its resolution was intended by the related containers work. If not, we can resolve separately from this PR.

**Comment by markmhendrickson** [comment]
Activity is loading quickly for me in this build. Let's also add an integration test per [this acceptance criterion](https://www.notion.so/trustmachines/Given-user-is-viewing-when-selecting-Activity-then-activity-content-loads-within-3-seconds-de0656438fc94e72a588de13fff79af4?pvs=4) to prevent a regression? cc @alter-eggo 

image

**Comment by markmhendrickson** [comment]
The logo shouldn't show up the "Add network" view when displayed in the action popup. Let's fix and add a test per [this acceptance criterion](https://www.notion.so/trustmachines/When-viewing-then-logo-should-not-appear-in-app-nav-0e29bfcd5e204f43849be4a3f3a3fb62?pvs=4).

In the title, "Add network" shouldn't capitalize "Network" either.

image

Note in production, it's displayed in full page view but not action popup, as desired.

image

**Update**: It appears this is a general issue across views loaded in the action popup. Anytime we have a back button, we should hide the logo?

image

**Comment by markmhendrickson** [comment]
Now that we've switched to Mempool.space, presumably the prefilled value for Bitcoin APIs when adding networks should also be Mempool?

image

**Comment by markmhendrickson** [comment]
Network menu styles look good 👌 

image

**Comment by markmhendrickson** [comment]
The receive view now has a dismissal option rather than a back option in the app nav. @fabric-8 @mica000 I presume the back option is desired for consistency with the other home options (e.g. send, swap, buy).

image


Note as well that the receive header has no top margin either as a result.

In production, the back button appears:

image

Let's add tests for these acceptance criteria as well:

- [Select token](https://www.notion.so/trustmachines/Select-token-fbed262549b04816b08e78866e2fedb7?pvs=4)
- [Receive assets](https://www.notion.so/trustmachines/Given-user-viewing-in-then-back-button-should-appear-in-app-navigation-and-no-logo-should-appear--8ba8a6c3e4674b11ad9594ae76000c49?pvs=4)
- [Swap assets](https://www.notion.so/trustmachines/Given-user-viewing-in-then-back-button-should-appear-in-app-navigation-and-no-logo-should-appear--81439d19ecd14bc0a5c4c97aa8f67055?pvs=4)

**Comment by markmhendrickson** [comment]
The app navs during the various API flows look good to me. 

Ideally we'd show the STX balance for the Stacks message signing variant, as we show BTC for Bitcoin message signing, but this enhancement isn't a blocker.

## Bitcoin message signing

image

## Bitcoin transaction

image

## PSBT

image

## Stacks message signing

image


## Stacks transaction

image

**Comment by markmhendrickson** [comment]
The latest build looks generally good in terms of the menu and app nav fixes. However, note that the menu for the state with no wallet configured has a remnant divider line which should ideally be removed as well:

Screenshot 2024-08-08 at 08 17 30

Note how it doesn't appear here when signed in:

Screenshot 2024-08-08 at 08 18 27



I overlooked flagging https://github.com/leather-io/extension/pull/5726#issuecomment-2273212430 yesterday as a blocker, but we'll need to resolve it before releasing this PR as well.

**Comment by fabric-8** [comment]
@mica000 Regarding back button vs. close, I agree that in the context of the popover it doesn't quite make sense from a user perspective why there would be a close for receive, but a back for the other screens.

CleanShot 2024-08-08 at 09 01 08@2x

Maybe we can just keep the "back" in the popover, but do use a close in fullscreen as already mocked up here earlier, as it's effectively a different kind of ux there? I'm not 100% sure wether that has been our intention all the ay or not since the version with "x" does exist on the same page as well

**Comment by markmhendrickson** [comment]
If needed to unblock this release today, we can also just add top padding to the receive view in the action popup format? 

The lack of consistent top padding there compared to other similar views (e.g. send, swap, buy) is what seems most in need of resolution. We can figure out later if we need to convert the receive view into a page (since it's basically a sheet at the moment, whereas these other views are pages?).

Let's take care to QA PRs on the original PRs themselves going forward. We're unfortunately trying to fix these container related issues now to unblock the more urgent release of Mempool support.

**Comment by fbwoolf** [comment]
@alter-eggo are you needing more eyes on testing this release or just code review?

**Comment by alter-eggo** [comment]
@fbwoolf more testing I think

**Comment by pete-watters** [comment]
> If needed to unblock this release today, we can also just add top padding to the receive view in the action popup format?
> 
> The lack of consistent top padding there compared to other similar views (e.g. send, swap, buy) is what seems most in need of resolution. We can figure out later if we need to convert the receive view into a page (since it's basically a sheet at the moment, whereas these other views are pages?).
> 
> Let's take care to QA PRs on the original PRs themselves going forward. We're unfortunately trying to fix these container related issues now to unblock the more urgent release of Mempool support.

Thanks for your help checking this @markmhendrickson  👍  Also thanks a lot to @alter-eggo for adding so many fixes here, I appreciate it. 

In future, if we need to do a release and issues are found like this, we should remove the offending commits from the release branch so it's not blocked rather than having it block more urgent things. 

I am checking through the updates made and will add some better tests to catch issues next time. 

- this problem with the settings option: https://github.com/leather-io/extension/pull/5726#issuecomment-2275067678 was noticed as `Settings` was previously not available if the user has no wallet. I agree it is a good enhancement to get it working but it was a mistake by me to show the button there
- I will add this enhancement to show the balance in STX - https://github.com/leather-io/extension/pull/5726#issuecomment-2273305693 
- you are correct Mark on this discussion around the `Back` button https://github.com/leather-io/extension/pull/5726#issuecomment-2273146292. It's supposed to be a back button in action popup for consistency across flows. I will try and add a test to assert that it shows up on smaller screen sizes

**Pull request merged**
