### PR TITLE
feat: show stx balance on choose account screen

### LINKED ISSUE #1403: Show total balances in accounts selection menu
I've found several times now that I wanted to look for my account with a particular balance, but it's hard to do so since I have to select one at a time and check. It'd be nice to see the total balances at a glance from the accounts menu itself:

image

### PR DESCRIPTION
**Pull request by aulneau**
> Try out this version of the Stacks Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1060444948).

This was a quick little QOL improvement, resolves https://github.com/blockstack/stacks-wallet-web/issues/1403#issuecomment-885646427

Screen Shot 2021-07-23 at 9 41 49 AM

The designs have it `balance | address` but i opted for `address | balance` for two reasons: the address string never changes size, so it's more consistent  to be left aligned, and the balance might not show up if it's still loading.

cc/ @aulneau @kyranjamie @fbwoolf

### CODE REVIEW

**Comment by markmhendrickson** [comment]
Fantastic! Does this show up in the post-auth context as well?

image

**Comment by aulneau** [comment]
Screen Shot 2021-07-23 at 12 32 24 PM

**Review by fbwoolf — APPROVED** [review]
Looks good to me! 👍

**Review by beguene — APPROVED** [review]
Great idea !

**Pull request merged**
