### PR TITLE
feat: make ordinals occupy entire space

### LINKED ISSUE #3254: Make ordinal images occupy entire space
The black background should not be visible

image

### PR DESCRIPTION
**Pull request by edu-stx**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/4252265540).

Closes #3254

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Comment by fbwoolf** [comment]
@markmhx I approved this but then was thinking, are we sure this won't distort the image or make it blurry? Or, that a user did a small image intentionally?

**Comment by edu-stx** [comment]
Was having similar thoughts actually, will hold on merging.

**Comment by markmhendrickson** [comment]
I'll get this user to share the image and we can try it on for size before pushing. Stay tuned

**Comment by markmhendrickson** [comment]
https://ordinals.com/inscription/6b7fab5b7296cb078192fc6695c53143f6870b169a19a9bd3a2078c86c6a108bi0

@edu-stx want to use the dev console to swap in this image and see how it looks, sharing a screenshot here?

**Comment by markmhendrickson** [comment]
Actually sense because this is pixel art, that it should be fine. It shows up big at that link:

image

**Review by markmhendrickson — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
