### PR TITLE
chore: update runes avatar icon

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out Leather build 82da0a0 — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8695332094), [Test report](https://leather-wallet.github.io/playwright-reports/chore/update-runes-icon), [Storybook](https://chore-update-runes-icon--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=chore/update-runes-icon)

This PR updates the Runes avatar icon.

Screenshot 2024-04-15 at 2 08 57 PM

### CODE REVIEW

**Comment by fbwoolf** [comment]
@mica000 do we want the colors to change in dark mode or they stay the same? The svg didn't come in with token colors but I can change them so they do work in dark mode, but I'm not sure that is supposed to happen with an icon?

Screenshot 2024-04-15 at 3 28 54 PM

**Review by pete-watters — APPROVED** [review]

**Review by alter-eggo — APPROVED** [review]

**Comment by mica000** [comment]
@fbwoolf yes, that would be great!

**Comment by fbwoolf** [comment]
@pete-watters you merged this before I could push up the change for dark mode, fyi.

**Comment by pete-watters** [comment]
> @pete-watters you merged this before I could push up the change for dark mode, fyi.

Yes, I just needed the new icon for https://github.com/leather-wallet/extension/pull/5237, sorry if it was a hassle for you.

I saw your comment about dark mode but wanted to get the new icon

**Pull request merged**
