### PR TITLE
feat: add ordinals addresses in receive modal

### LINKED ISSUE #3229: Add Ordinal address option to "receive" asset screen and or change copy
I noticed a user sending their ordinal here:
image

We may want to edit the copy here: "Share your account's unique address to receive any token or collectable"
To make it clear that this bitcoin address it not to be used for Ordinals

Could we possibly add a line for an Ordinal address?
image

Show the warning before copy here too?

### PR DESCRIPTION
**Pull request by alter-eggo**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/4277922042).

This pr closes https://github.com/hirosystems/stacks-wallet-web/issues/3229

### CODE REVIEW

**Comment by alter-eggo** [comment]
@kyranjamie I fixed comments mentioned in https://github.com/hirosystems/stacks-wallet-web/pull/3259

**Comment by mica000** [comment]
Screenshot 2023-02-23 at 18 59 29


This element needs some styling fixes and the subtitle can be removed

svg:
Error

Font size should be 14px

Screenshot 2023-02-23 at 19 04 26

**Comment by mica000** [comment]
Screenshot 2023-02-23 at 18 59 14
 Could you also fix the font size for the section? I updated to body 2 (14px)

**Comment by mica000** [comment]
The ability to quickly copy a BTC address can be removed from the modal as well and from the header. This is beacuse the user needs to see the notification before.

Screenshot 2023-02-23 at 18 59 08

Screenshot 2023-02-23 at 18 58 55

@markmhx Save to say we can remove the ability to copy STX address from the header as well on this PR?

**Comment by markmhendrickson** [comment]
> Save to say we can remove the ability to copy STX address from the header as well on this PR?

Yep!

**Comment by alter-eggo** [comment]
@mica000  I removed copy icons, and added separator. but do these truncated addresses really make much sense to user? 
Screenshot 2023-02-23 at 23 59 55

**Comment by markmhendrickson** [comment]
I think @mica000 might mean removing both the copy buttons and the address values entirely, showing just the total fiat value of BTC and STX per https://github.com/hirosystems/stacks-wallet-web/issues/3132#issuecomment-1433124048

**Comment by mica000** [comment]
We can remove these addresses:
Screenshot 2023-02-24 at 17 42 53

----
We can also remove the subtitle from the BTC receive step
Screenshot 2023-02-24 at 17 42 12

On the same step, the style of the address seems to be removed:
Screenshot 2023-02-24 at 17 42 16

**Comment by mica000** [comment]
Screenshot 2023-02-24 at 17 46 53
Screenshot 2023-02-24 at 17 46 47

The popover doesn't seem to contain the changes of this PR?

**Comment by alter-eggo** [comment]
@mica000 I removed subtitle from the BTC receive step

> We can remove these addresses:

I will do it in separate pr

> The popover doesn't seem to contain the changes of this PR?

hm, weird, for me it's ok
Screenshot 2023-02-24 at 21 47 24


probably you checked some other version?
Screenshot 2023-02-24 at 21 49 16

**Comment by mica000** [comment]
@alter-eggo Sorry, my bad then! Everything is looking good now! Thank you!

**Comment by markmhendrickson** [comment]
This looks good to ship!

A few nitpicks here to resolve afterwards as needed:

Screenshot 2023-02-24 at 15 08 53

- Should say "Do not deposit **Ordinal inscriptions** here"
- The entire second line should be linked, inclusive of "Use the" since otherwise it seems a bit weird?
- We can remove the period from the end of the second line

cc @mica000

**Comment by alter-eggo** [comment]
done

**Review by fbwoolf — APPROVED** [review]

**Pull request merged**
