### PR TITLE
fix validate custom network name field on form submission

### LINKED ISSUE #4737: Empty Test Displayed When Creating a Custom Network Without a Name
In the header, the network badge text appears empty when a custom testnet network is added without a name.

Screenshot 2023-12-20 222406

Steps to reproduce:
1. In the settings, select **change network**.
2. click **add network.**
3. Choose from regtest, signet, or testnet.
4. After that, click **add network** without providing the network a name.

### PR DESCRIPTION
**Pull request by Nithishvb**
Closes #4737

This PR addresses and resolves the issue #4737, which focuses on enhancing the validation of the custom network name field in the form.

### CODE REVIEW

**Comment by pete-watters** [comment]
Thanks for fixing this @Nithishvb , I've verified the fix is working.

**Review by pete-watters — APPROVED** [review]

**Comment by Nithishvb** [comment]
Hi, @pete-watters , did I do anything to ensure that every check was approved?

**Comment by pete-watters** [comment]
> Hi, @pete-watters , did I do anything to ensure that every check was approved?

You did, and many thanks! I need to make some changes to the CI so I can get your PR merged. I will do this as soon as I can.

I appreciate your efforts helping us. As soon as I can solve those issues I will get both of your PRs merged.

**Comment by pete-watters** [comment]
I'll merge this here: https://github.com/leather-wallet/extension/pull/4823

**Pull request closed without merging**
