### PR TITLE
Release/testnet support

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out Leather build 22f727e — [Extension build](https://github.com/leather-wallet/extension/actions/runs/9546392276), [Test report](https://leather-wallet.github.io/playwright-reports/release-testnet-support), [Storybook](https://release-testnet-support--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=release-testnet-support)

**TO BE RELEASED ON MONDAY AFTER TESTING**

- https://github.com/leather-wallet/extension/pull/47
- https://github.com/leather-wallet/extension/pull/68
- https://github.com/leather-wallet/extension/issues/5070
- https://github.com/leather-wallet/extension/pull/5528
- https://github.com/leather-wallet/extension/issues/5529
- https://github.com/leather-wallet/extension/pull/5537

### CODE REVIEW

**Comment by fbwoolf** [comment]
cc @314159265359879 to test.

**Review by alter-eggo — APPROVED** [review]

**Comment by 314159265359879** [comment]
Tested this build: , these are my findings release/testnet-support#5048be3:

1. I see this error when I sign out on the wallet:
image
routing issue for this page when signed out? chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/index.html#/get-started

2. Sending STX through the send flow (Testnet and mainnet) ✅ (software wallet and hardware wallet)

2a. I saw this a couple times after sending STX transfer transaction in short succession: Nonce error when pending transaction. I see conflicting nonce in mempool error pop up here (wallet sets same nonce as previous transaction (i.e. 4) instead of nextNonce (i.e. 5)):
image this happens when there is a transaction pending and you create a new one. The next nonce is not properly set. 

2b. Looks like the submitted state isn't going away automatically when the pending state is registered by the wallet from a node?
submitted state even still showing when it is already confirmed. Submitted state should be hidden when the pending state is displayed. 
image

When I refresh (F5) the activity page the submitted ones do not show anymore
image

3. Loading issue, when I restore the wallet and enter the first account, looks like the loading crashed, more than 10 minutes of the loading animation and i see these errors in the console (I am not sure if they are related, looks like they similar ones showed again later):
image

````
 panicked at library/std/src/sys/wasm/../unsupported/thread.rs:26:9:
can't sleep

Stack:

Error
    at __wbg_new_abda76e883ba8a5f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:1221:17)
    at console_error_panic_hook::hook::h700155b3d69d9e0f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[889]:0x15e0c3)
    at core::ops::function::Fn::call::h47e2a6c7f27b8b9f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2953]:0x1bab11)
    at std::panicking::rust_panic_with_hook::h3178d1253937346b (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[1673]:0x1a1df1)
    at std::panicking::begin_panic_handler::{{closure}}::h76b7a67a31250e84 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[1880]:0x1ac509)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h4feff3b290e9e0ea (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2949]:0x1baaea)
    at rust_begin_unwind (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2222]:0x1b5c1f)
    at core::panicking::panic_fmt::h540dca0970a4f91d (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2283]:0x1b6b45)
    at std::thread::sleep::hf379721838e0df36 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2281]:0x1b6ac4)
    at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hac2102c8a71c786e (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[83]:0x2e638)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h2b25cb6c58a8bdec (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[879]:0x15cc6e)
    at wasm_bindgen::convert::closures::invoke1_mut::h9cf84b7b6502f00d (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2437]:0x1b8897)
    at __wbg_adapter_30 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:702:10)
    at real (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:687:20)
````
and
````
32ab8b9….module.wasm:1 Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (32ab8b9fe567fac2a408.module.wasm)
    at rust_panic (32ab8b9fe567fac2a408.module.wasm)
    at std::panicking::rust_panic_with_hook::h3178d1253937346b (32ab8b9fe567fac2a408.module.wasm)
    at std::panicking::begin_panic_handler::{{closure}}::h76b7a67a31250e84 (32ab8b9fe567fac2a408.module.wasm)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h4feff3b290e9e0ea (32ab8b9fe567fac2a408.module.wasm)
    at rust_begin_unwind (32ab8b9fe567fac2a408.module.wasm)
    at core::panicking::panic_fmt::h540dca0970a4f91d (32ab8b9fe567fac2a408.module.wasm)
    at std::thread::sleep::hf379721838e0df36 (32ab8b9fe567fac2a408.module.wasm)
    at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hac2102c8a71c786e (32ab8b9fe567fac2a408.module.wasm)
    at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h2b25cb6c58a8bdec (32ab8b9fe567fac2a408.module.wasm)
    at wasm_bindgen::convert::closures::invoke1_mut::h9cf84b7b6502f00d (32ab8b9fe567fac2a408.module.wasm)
    at __wbg_adapter_30 (90.js:702:10)
    at real (90.js:687:20)
````

4. sometimes it takes long for the fee to load (seen on mainnet and testnet) (throttling?), and this error is seen:
image

5. Signing contract call transactions (mainnet and testnet) ✅ 
5a. Testnet: Creating offers and matching swaps, cancelling offers on beefyswap.io ✅ is working without issue using this build.

6. Deploying smart contract ✅ 

X. Loading issue, stacks not showing, I believe this is fixed in another PR, this one: https://github.com/leather-wallet/extension/issues/5466
image

**Comment by fbwoolf** [comment]
> Tested this build: , these are my findings release/testnet-support#5048be3:
> 
> 1. I see this error when I sign out on the wallet:
>    image
>    routing issue for this page when signed out? chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/index.html#/get-started
>
This is a known existing bug not specific to this release, correct?

> 2. Sending STX through the send flow (Testnet and mainnet) ✅ (software wallet and hardware wallet)
> 
> 2a. I saw this a couple times after sending STX transfer transaction in short succession: Nonce error when pending transaction. I see conflicting nonce in mempool error pop up here (wallet sets same nonce as previous transaction (i.e. 4) instead of nextNonce (i.e. 5)): image this happens when there is a transaction pending and you create a new one. The next nonce is not properly set.
> 
I think this surfaces when the api is slow?

> 2b. Looks like the submitted state isn't going away automatically when the pending state is registered by the wallet from a node? submitted state even still showing when it is already confirmed. Submitted state should be hidden when the pending state is displayed. image
> 
> When I refresh (F5) the activity page the submitted ones do not show anymore image
> 
I didn't think this was different in production, but it is hard for me to consistently get the submitted state. Can you test production and report back? I will try to test again on my end.

> 3. Loading issue, when I restore the wallet and enter the first account, looks like the loading crashed, more than 10 minutes of the loading animation and i see these errors in the console (I am not sure if they are related, looks like they similar ones showed again later):
>    image
> 
> ```
>  panicked at library/std/src/sys/wasm/../unsupported/thread.rs:26:9:
> can't sleep
> 
> Stack:
> 
> Error
>     at __wbg_new_abda76e883ba8a5f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:1221:17)
>     at console_error_panic_hook::hook::h700155b3d69d9e0f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[889]:0x15e0c3)
>     at core::ops::function::Fn::call::h47e2a6c7f27b8b9f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2953]:0x1bab11)
>     at std::panicking::rust_panic_with_hook::h3178d1253937346b (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[1673]:0x1a1df1)
>     at std::panicking::begin_panic_handler::{{closure}}::h76b7a67a31250e84 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[1880]:0x1ac509)
>     at std::sys_common::backtrace::__rust_end_short_backtrace::h4feff3b290e9e0ea (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2949]:0x1baaea)
>     at rust_begin_unwind (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2222]:0x1b5c1f)
>     at core::panicking::panic_fmt::h540dca0970a4f91d (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2283]:0x1b6b45)
>     at std::thread::sleep::hf379721838e0df36 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2281]:0x1b6ac4)
>     at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hac2102c8a71c786e (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[83]:0x2e638)
>     at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h2b25cb6c58a8bdec (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[879]:0x15cc6e)
>     at wasm_bindgen::convert::closures::invoke1_mut::h9cf84b7b6502f00d (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2437]:0x1b8897)
>     at __wbg_adapter_30 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:702:10)
>     at real (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:687:20)
> ```
> 
> and
> 
> ```
> 32ab8b9….module.wasm:1 Uncaught (in promise) RuntimeError: unreachable
>     at __rust_start_panic (32ab8b9fe567fac2a408.module.wasm)
>     at rust_panic (32ab8b9fe567fac2a408.module.wasm)
>     at std::panicking::rust_panic_with_hook::h3178d1253937346b (32ab8b9fe567fac2a408.module.wasm)
>     at std::panicking::begin_panic_handler::{{closure}}::h76b7a67a31250e84 (32ab8b9fe567fac2a408.module.wasm)
>     at std::sys_common::backtrace::__rust_end_short_backtrace::h4feff3b290e9e0ea (32ab8b9fe567fac2a408.module.wasm)
>     at rust_begin_unwind (32ab8b9fe567fac2a408.module.wasm)
>     at core::panicking::panic_fmt::h540dca0970a4f91d (32ab8b9fe567fac2a408.module.wasm)
>     at std::thread::sleep::hf379721838e0df36 (32ab8b9fe567fac2a408.module.wasm)
>     at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hac2102c8a71c786e (32ab8b9fe567fac2a408.module.wasm)
>     at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h2b25cb6c58a8bdec (32ab8b9fe567fac2a408.module.wasm)
>     at wasm_bindgen::convert::closures::invoke1_mut::h9cf84b7b6502f00d (32ab8b9fe567fac2a408.module.wasm)
>     at __wbg_adapter_30 (90.js:702:10)
>     at real (90.js:687:20)
> ```
> 
Not sure about this one, seems like an api issue loading the balance. I don't think the errors in the console are related.

> 4. sometimes it takes long for the fee to load (seen on mainnet and testnet) (throttling?), and this error is seen:
>    image
>
This is a known issue with the fee endpoint loading slow?

> 5. Signing contract call transactions (mainnet and testnet) ✅
>    5a. Testnet: Creating offers and matching swaps, cancelling offers on beefyswap.io ✅ is working without issue using this build.
> 6. Deploying smart contract ✅
> 
> X. Loading issue, stacks not showing, I believe this is fixed in another PR, this one: #5466 image
>
Yep, I'm working on fixing this in the PR you linked. 👍

**Comment by 314159265359879** [comment]
> > Tested this build: , these are my findings release/testnet-support#5048be3:
> > 
> > 1. I see this error when I sign out on the wallet:
> >    image
> >    routing issue for this page when signed out? chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/index.html#/get-started
> 
> This is a known existing bug not specific to this release, correct?
> 

I have only seen this in this PR. I don't think it is an existing issue, I do not see the issue on 6.42.0 (current production version). 

> > 2. Sending STX through the send flow (Testnet and mainnet) ✅ (software wallet and hardware wallet)
> > 
> > 2a. I saw this a couple times after sending STX transfer transaction in short succession: Nonce error when pending transaction. I see conflicting nonce in mempool error pop up here (wallet sets same nonce as previous transaction (i.e. 4) instead of nextNonce (i.e. 5)): image this happens when there is a transaction pending and you create a new one. The next nonce is not properly set.
> 
> I think this surfaces when the api is slow?
> 

That would also be my guess, although I am not sure if it has something to do with 2b. 

I am not sure if the initial issue was also concerning transactions send in rapid succession. 

> > 2b. Looks like the submitted state isn't going away automatically when the pending state is registered by the wallet from a node? submitted state even still showing when it is already confirmed. Submitted state should be hidden when the pending state is displayed. image
> > When I refresh (F5) the activity page the submitted ones do not show anymore image
> 
> I didn't think this was different in production, but it is hard for me to consistently get the submitted state. Can you test production and report back? I will try to test again on my end.
> 

I do not see this testing with the production version on mainnet, and although harder to test reliably on testnet with 6.42.0 because of the other issues with testnet. There it does make the "submitted" state get replaced automatically after it is seen in the mempool. 

> > 3. Loading issue, when I restore the wallet and enter the first account, looks like the loading crashed, more than 10 minutes of the loading animation and i see these errors in the console (I am not sure if they are related, looks like they similar ones showed again later):
> >    image
> > 
> > ```
> >  panicked at library/std/src/sys/wasm/../unsupported/thread.rs:26:9:
> > can't sleep
> > 
> > Stack:
> > 
> > Error
> >     at __wbg_new_abda76e883ba8a5f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:1221:17)
> >     at console_error_panic_hook::hook::h700155b3d69d9e0f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[889]:0x15e0c3)
> >     at core::ops::function::Fn::call::h47e2a6c7f27b8b9f (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2953]:0x1bab11)
> >     at std::panicking::rust_panic_with_hook::h3178d1253937346b (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[1673]:0x1a1df1)
> >     at std::panicking::begin_panic_handler::{{closure}}::h76b7a67a31250e84 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[1880]:0x1ac509)
> >     at std::sys_common::backtrace::__rust_end_short_backtrace::h4feff3b290e9e0ea (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2949]:0x1baaea)
> >     at rust_begin_unwind (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2222]:0x1b5c1f)
> >     at core::panicking::panic_fmt::h540dca0970a4f91d (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2283]:0x1b6b45)
> >     at std::thread::sleep::hf379721838e0df36 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2281]:0x1b6ac4)
> >     at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hac2102c8a71c786e (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[83]:0x2e638)
> >     at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h2b25cb6c58a8bdec (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[879]:0x15cc6e)
> >     at wasm_bindgen::convert::closures::invoke1_mut::h9cf84b7b6502f00d (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/32ab8b9….module.wasm:wasm-function[2437]:0x1b8897)
> >     at __wbg_adapter_30 (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:702:10)
> >     at real (chrome-extension://ngplfhjihnakkkpciijhjkkmobjfdfcn/90.js:687:20)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and
> > ```
> > 32ab8b9….module.wasm:1 Uncaught (in promise) RuntimeError: unreachable
> >     at __rust_start_panic (32ab8b9fe567fac2a408.module.wasm)
> >     at rust_panic (32ab8b9fe567fac2a408.module.wasm)
> >     at std::panicking::rust_panic_with_hook::h3178d1253937346b (32ab8b9fe567fac2a408.module.wasm)
> >     at std::panicking::begin_panic_handler::{{closure}}::h76b7a67a31250e84 (32ab8b9fe567fac2a408.module.wasm)
> >     at std::sys_common::backtrace::__rust_end_short_backtrace::h4feff3b290e9e0ea (32ab8b9fe567fac2a408.module.wasm)
> >     at rust_begin_unwind (32ab8b9fe567fac2a408.module.wasm)
> >     at core::panicking::panic_fmt::h540dca0970a4f91d (32ab8b9fe567fac2a408.module.wasm)
> >     at std::thread::sleep::hf379721838e0df36 (32ab8b9fe567fac2a408.module.wasm)
> >     at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::hac2102c8a71c786e (32ab8b9fe567fac2a408.module.wasm)
> >     at wasm_bindgen_futures::queue::Queue::new::{{closure}}::h2b25cb6c58a8bdec (32ab8b9fe567fac2a408.module.wasm)
> >     at wasm_bindgen::convert::closures::invoke1_mut::h9cf84b7b6502f00d (32ab8b9fe567fac2a408.module.wasm)
> >     at __wbg_adapter_30 (90.js:702:10)
> >     at real (90.js:687:20)
> > ```
> 
> Not sure about this one, seems like an api issue loading the balance. I don't think the errors in the console are related.
> 
> > 4. sometimes it takes long for the fee to load (seen on mainnet and testnet) (throttling?), and this error is seen:
> >    image
> 
> This is a known issue with the fee endpoint loading slow?
> 

It probably is, then it is just getting ridiculous how often I hit this. *cry*

> > 5. Signing contract call transactions (mainnet and testnet) ✅
> >    5a. Testnet: Creating offers and matching swaps, cancelling offers on beefyswap.io ✅ is working without issue using this build.
> > 6. Deploying smart contract ✅
> > 
> > X. Loading issue, stacks not showing, I believe this is fixed in another PR, this one: #5466 image
> 
> Yep, I'm working on fixing this in the PR you linked. 👍
👍

**Comment by alter-eggo** [comment]
@314159265359879 could you please check https://github.com/leather-wallet/extension/pull/5535, this is fix for your 1st point

**Review by kyranjamie — APPROVED** [review]
Catching up, thanks for making the fixes

**Comment by fbwoolf** [comment]
@314159265359879 I did just test the submitted txs and it is working for me. Typically, when I use logs on my end, the state gets cleared rather quickly and moves from submitted > pending right away so I don't see it. I think if our forced refresh for activity `refreshAccountData(ms)` is too fast for the api, then I just needed to wait from the query to rerun and it did clear automatically. If you wait a bit and refocus the window, does that force the query to refetch and clear it? Anyone else seeing the submitted txs not clear?

EDIT: Also, @314159265359879 in your image, the tx isn't listed in submitted and pending at the same time so that would be more of a bug? We could be more aggressive about refetching mempool txs, or create a greater delay in ms to do the forced refresh, if that would be helpful?

**Comment by pete-watters** [comment]
The error on signout was a known issue but I can't find the bug. It was assigned to me previously. 

I think the WASM issue relates to DLC link:
- https://github.com/leather-wallet/extension/issues/5244 
- https://github.com/leather-wallet/issues/issues/69

**Comment by 314159265359879** [comment]
> @314159265359879 I did just test the submitted txs and it is working for me. Typically, when I use logs on my end, the state gets cleared rather quickly and moves from submitted > pending right away so I don't see it. I think if our forced refresh for activity `refreshAccountData(ms)` is too fast for the api, then I just needed to wait from the query to rerun and it did clear automatically. If you wait a bit and refocus the window, does that force the query to refetch and clear it? Anyone else seeing the submitted txs not clear?
> 
> EDIT: Also, @314159265359879 in your image, the tx isn't listed in submitted and pending at the same time so that would be more of a bug? We could be more aggressive about refetching mempool txs, or create a greater delay in ms to do the forced refresh, if that would be helpful?

I rechecked this and it is caused by a difference in API performance for testnet. I do not see it on mainnet.  We don't need a chance here. If I do see this come up on the mainnet I will create a new issue for it on

**Pull request merged**
