### PR TITLE
integrate LNSwap

### LINKED ISSUE #4558: Integrate LNSwap into swap screen
https://www.lnswap.org/

For swapping BTC – either via Lightning or not – onto Stacks as STX or xUSD

[See project](https://www.notion.so/trustmachines/Add-LNSwap-support-to-swaps-BTC-Stacks-b0d24b27fa924292b7d13b97a52d508b)

### PR DESCRIPTION
**Pull request by pseudozach**
fixes #4558 

some open design/UX questions on this:
- How to enable a swap LNBTC -> STX when LNBTC balance is 0 ?
- How should we take an LN invoice input from the user in case of STX -> LNBTC ?
- Should lnswap sdk return a transaction for leather to sign (similar to what Alex SDK does) or can I just return created swap data that includes the contract address, amount and contract call parameters and prepare the payment on leather repo lnswap related components?

### CODE REVIEW

**Comment by markmhendrickson** [comment]
@pseudozach thanks! Mind including a screen recording walkthrough of how this currently works?

**Comment by kyranjamie** [comment]
> How to enable a swap LNBTC -> STX when LNBTC balance is 0 ?

Can you elaborate on this. How would you be able to swap in the first place if your balance is zero? Is that how it works?

Other questions are design related. ~Do we have designs for LNSwap specific swapping flows?~ Edit [see them here.](https://www.figma.com/file/nY5UTVUoJdLQ30sk7YGQ3Y/%F0%9F%94%81-Swap?type=design&node-id=201-17001&mode=design&t=v9uU3JtbPjYvFKX6-0). Imagine we need to update these with the latter questions re accepting invoice etc.

**Comment by pseudozach** [comment]
> > How to enable a swap LNBTC -> STX when LNBTC balance is 0 ?
> 
> Can you elaborate on this. How would you be able to swap in the first place if your balance is zero? Is that how it works?
> 
> Other questions are design related. ~Do we have designs for LNSwap specific swapping flows?~ Edit [see them here.](https://www.figma.com/file/nY5UTVUoJdLQ30sk7YGQ3Y/%F0%9F%94%81-Swap?type=design&node-id=201-17001&mode=design&t=v9uU3JtbPjYvFKX6-0). Imagine we need to update these with the latter questions re accepting invoice etc.

I meant if user wants to use some other way to pay a Lightning invoice and then receive STX in their leather wallet. how do we enable that? I noticed in the codebase if a balance is 0, it wont show up in the list of swap pairs.

also I'm still trying to find an alternative way to test this end to end since both bitcoin and stacks testnet are unusable. I'll try to have a demo on regtest - devnet soon.

**Comment by kyranjamie** [comment]
This was an investigatory PR which now isn't being worked on. Closing.

**Pull request closed without merging**
