### PR TITLE
fix(ui): center dialog header

### LINKED ISSUE #5470: UI fix: Center align title - Title on the header of send ordinals is moving to the left
image

PS: On swap I believe the tile was gone but now that the feature is disabled I cant see anymore.

### PR DESCRIPTION
**Pull request by cbadawi**
fixes issue #5470

the header content was not properly centered due to the presence of the HeaderActionButton within the flex container. The HeaderActionButton was impacting the alignment of the header content, causing it to be off-center.

Added a "|" in a flex container under the header _locally_ to show the actual center point.

Before :
Screenshot 2024-06-23 at 4 13 45 PM

After :
Screenshot 2024-06-23 at 4 13 33 PM

When showing an asset list in the dialog, its a minimal ui bug. The misalignment becomes more visible with the no-tokens-found component in the token manager pr ( or if any component is centered in the dialog). So ideally the issue should be fixed before that pr.

Screenshot 2024-06-21 at 11 00 01 AM

## Summary by CodeRabbit

- **New Features**
  - Added a new `position` prop with a value of "absolute" to the `HeaderActionButton` component.

- **Bug Fixes**
  - Simplified conditional logic in `CurrentStacksAccountLoader` for better performance.
  - Improved loading state handling in various components by renaming `isInitialLoading` to `isLoading`.

- **Enhancements**
  - Updated `@leather.io/query` package to version `0.9.1`.
  - Refined balances handling and calculation in `use-total-balance` hook.
  - Enhanced `SendButtonSuspense` to disable based on `btcAddress` presence.

- **Refactor**
  - Renamed loader components and props for better clarity and consistency across the application.

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]
This might cause issues with longer headers, but think that's okay as it's an improvement as is and we don't have many longer headers.

**Comment by pete-watters** [comment]
Thanks for fixing this @cbadawi 👏  

I'd like to get it merged. Could you please help out by rebasing the branch so that it just has one commit for your actual change? 

We usually reference the issue in the commit message too so if you could do that it would be great. e.g. `fix(ui): center header,  ref leather-wallet/extension#64`

**Comment by cbadawi** [comment]
@pete-watters had some issues with my git config & author date but it should be fine as far as i can tell

**Comment by pete-watters** [comment]
> cbadawi

Everything looks good to me. Thanks for fixing this, your contribution is much appreciated and it's a big impact one line change. 

I got your work merged here: https://github.com/leather-io/extension/pull/5573 

In case it helps you in the future you can do `git commit --amend --reset-author` if you want to update the timestamp but it's not a big deal

**Pull request closed without merging**
