### PR TITLE
feat: send ordinals

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/4316522000).

Opening a new branch so I don't need to force push rebasing with dev on the wip branch (just in case).

This PR adds sending ordinals. Sending is hooked up here and working.

@kyranjamie @edu-stx for tomorrow:
- I rebased this branch and fixed merged conflicts in three files you should look over them to make sure I resolved the conflicts correctly. The three files are listed on the wip closed PR as having conflicts.
- I had to duplicate some components here to get past dep cruiser checks, but I made comments by them so we can refactor later.
- There are two files that had type errors I marked. I ended up using `any` bc I wasn't sure what the difference was b/w `Inscription` type and the one being used in the supporting components, `OrdinalInfo`.

### CODE REVIEW

**Comment by markmhendrickson** [comment]
Let's link this unit from within the send form to the ordinal view page on ordinals.com?

image

**Comment by markmhendrickson** [comment]
Let's also not switch to the "Activity" tab on submission but rather keep on the "Balances" one

image

**Comment by markmhendrickson** [comment]
A couple quick wins for this prompt could be:

- Change title to "Ordinal inscription" from "Send"
- Change button label to "Send" from "Continue"

That way it it's more of a ordinal viewer than just send form (given we want to link to the full page from here re the comment above)

cc @mica000 

Screenshot 2023-03-01 at 16 19 54

**Comment by fbwoolf** [comment]
> Let's link this unit from within the send form to the ordinal view page on ordinals.com?
> 
Why would we want them to leave the send form at that point?

EDIT: I did not implement this yet bc of the type issues that need to be resolved.

**Comment by fbwoolf** [comment]
> Let's also not switch to the "Activity" tab on submission but rather keep on the "Balances" one
> 
This is fixed.

**Comment by fbwoolf** [comment]
> A couple quick wins for this prompt could be:
> 
> * Change title to "Ordinal inscription" from "Send"
> * Change button label to "Send" from "Continue"
> 
I changed these.

**Comment by markmhendrickson** [comment]
> Let's link this unit from within the send form to the ordinal view page on ordinals.com?
> Why would we want them to leave the send form at that point?

It may be a bit of a temporary thing, but until we place a "Send" button inside the inscription listing under "Collectibles", alongside a separate "View" one (or enabling the whole area as the view action), this would be the only path to view the inscription on a full webpage.

We might also want to keep this modal as a generic viewer and do more with it (i.e. anything that we don't want to force into the collectibles area itself as part of the grid listing).

cc @mica000

**Comment by markmhendrickson** [comment]
It appears the recipient address doesn't yet show up on the confirm screen:

image

It looks like we need to add a row to this screen in [the Figma designs](https://github.com/hirosystems/stacks-wallet-web/issues/3184#issuecomment-1448363613).

**Comment by mica000** [comment]
> A couple quick wins for this prompt could be:
> 
> * Change title to "Ordinal inscription" from "Send"
> * Change button label to "Send" from "Continue"
> 
> That way it it's more of a ordinal viewer than just send form (given we want to link to the full page from here re the comment above)
> 
> cc @mica000

----
Seems like we have skipped a few details. Here are the designs for reference:

Send-1
Send-2
Send-3

**Comment by mica000** [comment]
> > Let's link this unit from within the send form to the ordinal view page on ordinals.com?
> > Why would we want them to leave the send form at that point?
> 
> It may be a bit of a temporary thing, but until we place a "Send" button inside the inscription listing under "Collectibles", alongside a separate "View" one (or enabling the whole area as the view action), this would be the only path to view the inscription on a full webpage.
> 
> We might also want to keep this modal as a generic viewer and do more with it (i.e. anything that we don't want to force into the collectibles area itself as part of the grid listing).
> 
> cc @mica000
-----
Are we not implementing the "send" button inside the collectibles anymore? 
If so, how are users able to select the ordinal to send? 

The link to the Ordinals detail page also happens on the collectible card:
Screenshot 2023-03-02 at 10 43 15

We can however also add a view details action on the send but I agree with Fara that this would make them leave the send form:
Screenshot 2023-03-02 at 10 55 26

**Comment by mica000** [comment]
Screenshot 2023-03-02 at 10 46 41
Screenshot 2023-03-02 at 10 46 31



🧹🧹🧹🧹🙏🏻

If possible to be fixed on this PR, can we make sure the corner radius are:
16px for Modal
10px for container
8px for image

These border radius are a bit tricky to make an universal value because to make proportional, each inner component decreases the radius, and making them all the same makes the component looks quite sloppy 😅

**Comment by edu-stx** [comment]
Just pushed a commit that reverts two of my earlier commits in this branch. Those commits were just being used to allow me to work on a more up to date version of the codebase and were meant to be (and already have been) merged to dev separately

reverting commit: `569a7f97...`

reverts: `8bb3fdc3...`, `c7656675...`

**Comment by fbwoolf** [comment]
> Just pushed a commit that reverts two of my earlier commits in this branch. Those commits were just being used to allow me to work on a more up to date version of the codebase and were meant to be (and already have been) merged to dev separately
> 
Thanks, was confused about this when rebasing. 👍

**Review by kyranjamie — APPROVED** [review]

**Review by edu-stx — APPROVED** [review]

**Pull request merged**
