### PR TITLE
refactor: add bstk jwt payload validation

### PR DESCRIPTION
**Pull request by kyranjamie**
I thought we should add payload validation. Thinking there may be a schema in auth to validate against, realised there's a validation function exposed by the library itself.

### CODE REVIEW

**Review by hstove — APPROVED** [review]

**Comment by markmhendrickson** [comment]
Is this ready to merge or should we pass to QA?

**Comment by markmhendrickson** [comment]
@timstackblock needs authentication smoke test

**Comment by timstackblock** [comment]
Double blockstack logo regression in this build, please fix and move back to QA

Screen Shot 2020-11-23 at 8 46 20 AM

**Comment by markmhendrickson** [comment]
The logo fix was merged 5 days with https://github.com/blockstack/ux/issues/629 whereas this PR was spun up 14 days ago, so I presume it's simply a matter of rebasing master into this branch and smoke testing again.

@kyranjamie mind doing that and assigning back to @timstackblock ?

**Comment by kyranjamie** [comment]
Rebased.

**Comment by hstove** [comment]
Closing - new PR is #752 , which has the same code but in the new `doSaveAuthRequest` location. Thanks Kyran!

**Pull request closed without merging**
