### PR TITLE
Release/2022 07 26 radical raccoon

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2776278823).

Contents:

- https://github.com/hirosystems/stacks-wallet-web/pull/2577
- https://github.com/hirosystems/stacks-wallet-web/pull/2582
- https://github.com/hirosystems/stacks-wallet-web/pull/2587

cc/ @kyranjamie @fbwoolf

### CODE REVIEW

**Comment by fbwoolf** [comment]
@kyranjamie I tested this and seems good to release. If you can test it on your end and approve it, maybe I can release it tomorrow morning?

**Review by kyranjamie — APPROVED** [review]

**Comment by markmhendrickson** [comment]
@fbwoolf Is this the corresponding release? https://github.com/hirosystems/stacks-wallet-web/releases/tag/v3.13.2

It seems like we might be able to flesh out the release notes more with links to the issues resolved.

**Comment by fbwoolf** [comment]
> 
> It seems like we might be able to flesh out the release notes more with links to the issues resolved.
>
Not sure what you mean by this? Our release notes are generated in a Github workflow: https://github.com/hirosystems/stacks-wallet-web/blob/34155a105e88b61a586fc0afd9c140d139422a8a/.github/workflows/create-version.yml#L41

**Comment by fbwoolf** [comment]
I think the release notes are not picking up the tag `refactor`.

**Pull request merged**
