### PR TITLE
chore: additional checks before adding tapInternalKey

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of Leather — [Extension build](https://github.com/leather-wallet/extension/actions/runs/7845648043), [Test report](https://leather-wallet.github.io/playwright-reports/fix/tap-internal-key-added)

Ref #4125

Not entirely sure if this is appropriate logic, but if I understand correctly, the additional check ensures TR script spends don't automatically have the `tapInternalKey` added, invalidating the tx.

We should sunset auto-adding of `tapInternalKey` as it's a bit of a naive solution I think. Instead, developers should be taught to add it rather than relying on some implicit tx mutating behaviour.

cc/ @gregdhill

### CODE REVIEW

**Comment by kyranjamie** [comment]
@gregdhill to test and confirm if fixed

**Comment by gregdhill** [comment]
Just tested and now works for script-path spends @kyranjamie :tada:

**Review by fbwoolf — APPROVED** [review]

**Comment by danielsimao** [comment]
@kyranjamie this is yet to be released correct?

**Comment by kyranjamie** [comment]
@danielsimao this will be included in our next release

**Pull request merged**
