### PR TITLE
Release/2022 05 12 curious coyote

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2331947478).

Content:

- https://github.com/hirosystems/stacks-wallet-web/pull/2398
- https://github.com/hirosystems/stacks-wallet-web/pull/2401
- https://github.com/hirosystems/stacks-wallet-web/pull/2404
- https://github.com/hirosystems/stacks-wallet-web/pull/2411
- https://github.com/hirosystems/stacks-wallet-web/pull/2350
- https://github.com/hirosystems/stacks-wallet-web/pull/2399

cc/ @kyranjamie @fbwoolf @beguene @He1DAr

### CODE REVIEW

**Comment by fbwoolf** [comment]
@kyranjamie any thoughts here on best way to remove these duplicate commits on dev?

**Comment by kyranjamie** [comment]
Not without force pushing, no. Can you elaborate which ones are dupes?

**Comment by fbwoolf** [comment]
> Not without force pushing, no. Can you elaborate which ones are dupes?

Screen Shot 2022-05-13 at 7 58 20 AM

All the ones from the last release.

**Comment by fbwoolf** [comment]
@kyranjamie I will drop those commits from this branch locally and do a force push to fix the merge conflicts here so it builds for QA to test.

**Comment by fbwoolf** [comment]
@kyranjamie unfortunately that doesn't work bc in order to fix the conflicts I have to rebase on dev which just adds the commits back ...so, will have to fix the duplicate commits on dev first. I am reluctant to force push to dev, but can. I can save a copy of dev locally just in case, but not sure how else to fix unless I just drop those commits on dev and force push?

**Comment by kyranjamie** [comment]
It's not the end of the world if there are some dupes, but we should figuring out why this has happened to avoid next time.

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
