### PR TITLE
feat: brc-20 send

### PR DESCRIPTION
**Pull request by alter-eggo**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5141139605).

See title

### CODE REVIEW

**Comment by markmhendrickson** [comment]
"Send max" seems to add unnecessary decimals? I have just 5 of this token here

Screenshot 2023-05-31 at 11 03 16

**Comment by markmhendrickson** [comment]
Also there's no error if I enter an amount exceeds my balance, and I'm able to continue to the next screen

Screenshot 2023-05-31 at 11 04 43

**Comment by markmhendrickson** [comment]
Let's also remove the "Recipient" input here and replace it with an info box, the same one as found [here](https://www.figma.com/file/3wsB9MwbKAI4CBL8Dt3x8V/Max-fee?type=design&node-id=49%3A7243&t=ajpBmNILkahUwVgM-1) in blue.

Header: Sending BRC-20 requires 2 steps
Body: 

> First submit here the amount you want to send and wait for a "transfer" inscription to appear in your wallet. 
> 
> Then send that inscription to your recipient of choice. [Learn more](#)

Screenshot 2023-05-31 at 11 16 30

@joshavenue Can you get a user guide into Gitbook that we can link from here? 🙏

**Comment by markmhendrickson** [comment]
Let's change the "Fee" label here to "Payment transaction fee" to distinguish better from "Inscription service fee"

Screenshot 2023-05-31 at 11 23 14

**Comment by markmhendrickson** [comment]
Here we should remove the recipient address and apply the same order of attributes (e.g. "Sending" in first place) as in the review screen, as well as same labels (e.g. "Payment transaction fee").

Replacing the recipient address (i.e. below the balance and above the other attributes), we should add another info box:

Screenshot 2023-05-31 at 11 27 26

Header: Sending BRC-20 requires 2 steps
Body:

> A new "transfer" inscription will appear in your wallet soon. 
> 
> Send that inscription to your recipient of choice to complete the transaction. Learn more

(with same URL for learn more as above in the send form)

Screenshot 2023-05-31 at 11 24 32

**Comment by markmhendrickson** [comment]
Let's modify this tooltip for BRC-20 specifically to "Total balance minus any amounts already represented by transfer inscriptions in your wallet"

Screenshot 2023-05-31 at 15 24 42

**Comment by markmhendrickson** [comment]
@alter-eggo we can use https://hirowallet.gitbook.io/guides/bitcoin/sending-brc-20-tokens for the Learn more URL here

**Comment by markmhendrickson** [comment]
I'm getting an invalid inscription error when trying to send an amount with decimals:

https://github.com/hirosystems/wallet/assets/28991/7d332846-c6c0-4f83-9ffb-5c0697050129

**Comment by markmhendrickson** [comment]
@mica000 think we need to increase the top or bottom margin for this new pending BRC-20 transfer section or somehow distinguish / divide it from the sections above and below a bit better? It seems a bit crunched to me

Screenshot 2023-05-31 at 16 55 09

**Comment by markmhendrickson** [comment]
I realized as well we can also add back these buttons to the send confirmation screen and link to the Bitcoin transaction emitted to pay for the inscription?

Screenshot 2023-05-31 at 16 59 04

**Comment by markmhendrickson** [comment]
Recipient address is showing up on review screen even though it's not entered previously

Screenshot 2023-05-31 at 18 16 11

**Comment by markmhendrickson** [comment]
Some updates to the two notices in the flow:

## On send form

Screenshot 2023-05-31 at 18 18 04

- Change header to "Sending BRC-20 tokens requires two steps
- Change body to:

```
1. Create transfer inscription with amount you want to send
2. Send transfer inscription to recipient of choice

Learn more
```


## On confirmation screen

Screenshot 2023-05-31 at 16 50 58

- Change header to "Sending requires another step"
- Replace body text to:

```
Send transfer inscription from home screen once status changes to "Ready to send transfer inscription"

Learn more
```

**Comment by markmhendrickson** [comment]
Is it easy enough to make this button label into "Create transfer inscription"

Screenshot 2023-05-31 at 18 30 55

And this header "Creating transfer inscription"

Screenshot 2023-05-31 at 18 31 06

**Comment by markmhendrickson** [comment]
@kyranjamie lemme know when decimal validation is removed and I'll test 🙏

**Comment by markmhendrickson** [comment]
@alter-eggo sorry for the notice copy thrash here. A couple more changes:

- simplify bullet point "1" in the first notice to "Create transfer inscription with amount to send" so fits onto one line
- extra line break before "Learn more" in both notices

Screenshot 2023-05-31 at 19 08 47
Screenshot 2023-05-31 at 19 11 02

**Comment by markmhendrickson** [comment]
As a nice to have, show total BTC here as another line:

Screenshot 2023-05-31 at 19 10 14

**Comment by markmhendrickson** [comment]
More nits for submitted screen 😅 


- Change notice header to "One more step is required to send tokens"
- Change notice copy to `You'll need to send the transfer inscription to your recipient of choice from the home screen once its status changes to "Ready to send"`
- "Sending" row should be first of three in bottom area
- Bonus: Add "Total fees" row to bottom
- "View details" should actually go to the "Pending BRC-20 transfers" on the home screen... can we deep / anchor link)
- Remove copy ID button

Screenshot 2023-05-31 at 19 11 29

**Comment by markmhendrickson** [comment]
We seem to need an error message ("Insufficient BTC available to pay fees") if the user doesn't have enough BTC to pay the fees. Right now the fees screen just refreshes upon submit


https://github.com/hirosystems/wallet/assets/28991/411b9ba7-9d01-4c3a-9213-c17c8e52133e

**Comment by joshavenue** [comment]
@markmhx Is there a version that I could access the UI for the BRC-20 sending functionality? So I can create the guide with all the screenshots.

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
