### PR TITLE
Release/mv3

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5578275196).

**TESTING**

Contents:

- MV3 changes
- https://github.com/hirosystems/wallet/issues/3954
- https://github.com/hirosystems/wallet/issues/3789
- https://github.com/hirosystems/wallet/issues/3871
- https://github.com/hirosystems/wallet/issues/2330

### CODE REVIEW

**Comment by fbwoolf** [comment]
@alter-eggo noticing with the secret key change here the textarea doesn't focus and there is no cursor, it is really hard to tell when the area is active until the typing or paster occurs.

**Comment by fbwoolf** [comment]
@kyranjamie have you tested the secret key blur changes here? I find it really hard to see?

**Comment by fbwoolf** [comment]
I haven't been able to test the build here, but I did rebase on dev to test my branch w/ the proposed fix to the disconnected port issue. I am still seeing the error during development on my branch.

**Comment by fbwoolf** [comment]
I tracked one idea that it might be related to a `sendResponse` callback not being called on `chrome.runtime.onMessage.addListener`?

**Comment by alter-eggo** [comment]
@fbwoolf yeah, agree here. fix: https://github.com/hirosystems/wallet/pull/3995

**Comment by fbwoolf** [comment]
@kyranjamie might this be relevant? https://bugs.chromium.org/p/chromium/issues/detail?id=1146434#c9

EDIT: I don't see that having devtools open disables it, but reading further down on possible solution...? https://bugs.chromium.org/p/chromium/issues/detail?id=1146434#c18

**Comment by fbwoolf** [comment]
@markmhx why was this assigned to me? I don't think I'm the best person to look into issues with MV3 changes. That was not my work.

**Comment by fbwoolf** [comment]
@kyranjamie I updated the release build here with your fix and tested it. All is working well for me. I confirmed the port disconnecting issue is fixed for me here too.

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
