### PR TITLE
Release/2022 06 23 kind koala

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2590145045).

Contents:

- https://github.com/hirosystems/stacks-wallet-web/pull/2242
- https://github.com/hirosystems/stacks-wallet-web/pull/2484
- https://github.com/hirosystems/stacks-wallet-web/pull/2452
- https://github.com/hirosystems/stacks-wallet-web/pull/2486
- https://github.com/hirosystems/stacks-wallet-web/pull/2487
- https://github.com/hirosystems/stacks-wallet-web/pull/2490
- https://github.com/hirosystems/stacks-wallet-web/pull/2492
- https://github.com/hirosystems/stacks-wallet-web/pull/2496

cc/ @kyranjamie @fbwoolf @beguene

### CODE REVIEW

**Comment by fbwoolf** [comment]
@beguene can you help me understand why I keep having to deal with merge conflicts when I merge main > dev to create a release PR? And, commits from main that have already been released are showing up here, is that bc I accidentally did a rebase and merge into main to cut the last release? Is there any way to clean this up? I believe if I try to drop the commits it will just tell me I have conflicts to resolve again?

**Comment by beguene** [comment]
@fbwoolf Yes indeed this is because of the rebase of the last release. The commits content are the same but the commit hashes are different that's why you get some 'duplicate' commit when you merge them back into dev.
Had it been a merge from dev into main, when you merge back main into dev git will know that those commits already exist in dev and you won't have any conflicts (at least not because of the added commits)

**Comment by fbwoolf** [comment]
> @fbwoolf Yes indeed this is because of the rebase of the last release.

Thanks for the feedback. 👍  I wish the PR button didn't default to `Rebase and merge`! 😆

**Comment by fbwoolf** [comment]
~~Testing the update path with this build, it appears the referer header changes create an error and white screen on refresh after the update...~~

Screen Shot 2022-06-25 at 1 46 47 PM

EDIT: Retried several times and seems ok, so I think was user error.
EDIT AGAIN: Tried checking out the v3.10.0 tag and updating locally ...and I see the error, so now I am thinking we should add a check there for safety?

**Review by kyranjamie — CHANGES_REQUESTED** [review]
It looks like the code to add referer headers breaks Firefox
image

**Comment by fbwoolf** [comment]
> It looks like the code to add referer headers breaks Firefox
>
Should we try to fix or revert that commit from the release?

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
