### PR TITLE
Release PR

### PR DESCRIPTION
**Pull request by beguene**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1693331994).

cc/ @kyranjamie @fbwoolf

### CODE REVIEW

**Comment by kyranjamie** [comment]
Haven't these changes already been released? 🤔

**Comment by fbwoolf** [comment]
> Haven't these changes already been released? 🤔

Nope, Beguene was going to release them after QA retested dev branch with his fix ...but he was out on Fri and we don't release on Fridays.

**Comment by fbwoolf** [comment]
I will approve it just so it's ready for him tomorrow.

**Review by fbwoolf — APPROVED** [review]

**Comment by beguene** [comment]
@kyranjamie Can you have a look at this failure https://github.com/hirosystems/stacks-wallet-web/runs/4805015777?check_suite_focus=true, it tries to merge into beta but it has a merge conflict. I think this happened because we did this unusual flow: revert some commits in main, add some changes in dev, then merge main back into dev.

**Comment by kyranjamie** [comment]
Fixed. Yeah this happens when `dev` is rebased and can't auto-merge to `beta`. Ideally we need a job to force reset `beta` when this happens.

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
