### PR TITLE
Release/warm bustling meerkat

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/4806127210).

Contents:

- https://github.com/hirosystems/wallet/issues/2824
- https://github.com/hirosystems/wallet/issues/3338
- https://github.com/hirosystems/wallet/issues/3550
- https://github.com/hirosystems/wallet/issues/3582
- https://github.com/hirosystems/wallet/issues/3582
- Fix to remove a network: https://github.com/hirosystems/wallet/commit/dcf3c40996d49de1055bca6f56a9e9b737439c98
- Other misc commits for code health

### CODE REVIEW

**Comment by fbwoolf** [comment]
I have tested the build here and lgtm.

**Comment by fbwoolf** [comment]
It appears @alter-eggo found a bug here and has put up a PR to fix. So, don't release until this is merged and the release branch is reset: https://github.com/hirosystems/wallet/pull/3595

EDIT: This has been merged and reset here.

**Comment by markmhendrickson** [comment]
@kyranjamie ready to review and release?

**Comment by kyranjamie** [comment]
Delayed until we return resp to app

**Comment by fbwoolf** [comment]
> Delayed until we return resp to app

PR here to merge: https://github.com/hirosystems/wallet/pull/3601

**Comment by kyranjamie** [comment]
Reset hard to dev

**Review by kyranjamie — APPROVED** [review]

**Comment by markmhendrickson** [comment]
Let's 🚢 ?

**Pull request merged**
