### PR TITLE
refactor: currency model imports

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out Leather build 57167dc — [Extension build](https://github.com/leather-io/extension/actions/runs/10956664328), [Test report](https://leather-io.github.io/playwright-reports/refactor-currency-type), [Storybook](https://refactor-currency-type--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=refactor-currency-type)

I made changes in the models pkg that need to be updated here.

### CODE REVIEW

**Comment by fbwoolf** [comment]
I also had to add two resolutions here for security audit failtures ...again with storybook addons.

**Review by kyranjamie — APPROVED** [review]
Thanks for making this naming change @fbwoolf, 1% more consistent 🧘🏼‍♂️

**Comment by fbwoolf** [comment]
It appears the failing send btc tests are hitting this...
https://github.com/leather-io/extension/blob/36a84dc5ea72044b918ea2ab20fdd26809580935/src/app/pages/send/send-crypto-asset-form/form/btc/btc-send-form.tsx#L116

When I try to send btc on testnet, I'm getting a wrong insufficient balance error...
Screenshot 2024-09-17 at 11 19 29 AM copy

Issue made here: https://github.com/leather-io/extension/issues/5854

cc @alter-eggo

**Comment by pete-watters** [comment]
> I also had to add two resolutions here for security audit failtures ...again with storybook addons.

Thanks @fbwoolf . I had to add some resolutions for storybook lately too. Maybe we can consider getting rid of storybook in the `extension` now and just using it in the UI libs?

**Pull request merged**
