### PR TITLE
Add sourcemaps

### LINKED ISSUE #2084: Add source map support
Errors are difficult to debug when given a stack trace because there's no source map support. 

Here's an example stack trace where source map support would have made it much easier to debug an issue:

image

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1586749647).

I'm not 100% sure this will work, but think we're good to test

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Comment by andresgalante** [comment]
Is this PR still valid? if so, can we merge it or move it to QA?

**Comment by kyranjamie** [comment]
This is a dev tooling task re sentry, doesn't require QA.

**Comment by andresgalante** [comment]
🚀 🐿️

**Review by fbwoolf — APPROVED** [review]

**Comment by andresgalante** [comment]
Can we merge this PR?

**Comment by kyranjamie** [comment]
It needs to be tested alongside a release to know if it works. We could merge now, but if it doesn't work, it might block a release (say, it were to fail).

**Comment by andresgalante** [comment]
@He1DAr Since you are at it with Sentry, I wanted to bring this PR up

**Pull request closed without merging**
