### PR TITLE
feat: ordinals support, and more

### LINKED ISSUE #3192: Link to inscription page from collectibles
Inscriptions currently link directly to the content instead of the details page eg https://ordinals.com/inscription/60265ff572a317f247d65104b1da66c6a09b2399c49d7604b76d3f5e553215ffi0

### LINKED ISSUE #3193: Show non-image inscriptions with placeholder image
Currently we don't display non-image inscriptions but should with a placeholder image.

@mica000 mind providing a design for this placeholder?

### PR DESCRIPTION
**Pull request by edu-stx**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/4224974159).

Closes #3192
Closes #3193

Supercedes https://github.com/hirosystems/stacks-wallet-web/pull/3181 & https://github.com/hirosystems/stacks-wallet-web/pull/3190

@fbwoolf's screenshots,

This PR adds the flow to copy a taproot address to receive an ordinal.

Screen Shot 2023-02-18 at 1 43 38 PM

Screen Shot 2023-02-18 at 1 42 55 PM

### CODE REVIEW

**Comment by kyranjamie** [comment]
1f35d4d
- `useCurrentAccount` was being used. Confusingly, this refers to stacks only stuff, so removed & renamed
- Afaict we want these queries to be cached at an account level, so using a value from the keychain for the key
- Adjusted derivation logic, previously we were deriving a new full path from the account index. I've added some safe guards to the fns, to check the HDKey passed is at the expected depth.

**Comment by fbwoolf** [comment]
We have to kill some integration tests here when we enable btc or they are just going to fail looking for the old send form. I think it might be best for me to rebase my PR moving the feature flag and enabling tests conditionally to be based off this work and merged in here?

**Comment by edu-stx** [comment]
@fbwoolf fine by me, at the end of the day all commits will be added to dev one way or another

**Comment by edu-stx** [comment]
Latest commit closes #3192 and #3193

**Comment by markmhendrickson** [comment]
The placeholder SVG doesn't seem to load, @fbwoolf can you help patch?

Screenshot 2023-02-19 at 15 23 09

**Comment by markmhendrickson** [comment]
Images for inscriptions are also not loading because src is using the URL value that should be used to link the inscription to detail view page. The src should be using the inscription content itself.

Screenshot_2023-02-19_at_13 00 17

**Comment by kyranjamie** [comment]
Let's make sure to tidy up the commits before merging

**Comment by 314159265359879** [comment]
I still see inverted images in dark mode in this build. Not sure if the fix was merged here. 
New send form has a couple oddities in this build, but I have seen differences elsewhere, lets check again when we have a version ready for release: 
1. when does the review button become clickable
2. (STX/BTC) balance not yet shown in lower right corner or did we place it nearer to the "max" button? 
3. in dark mode "max" button isn't very obvious

**Comment by edu-stx** [comment]
@314159265359879 that's fine, the fix is in dev

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
