### PR TITLE
Release/apis yamanut

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/3994941439).

There are duplicate commits listed here, as I think the last release was rebased somewhere along the line.

I've fixed these on dev, and we can just double merge them to avoid force pushing. 

- [x] @fbwoolf to check if I merged correctly
- [x] Investigate Firefox build not working
- [ ] QA

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Comment by fbwoolf** [comment]
When I pull dev there are uncommitted yarn.lock changes for me.

**Comment by fbwoolf** [comment]
@kyranjamie are you still stuck on why the FF upload failed here? https://github.com/hirosystems/stacks-wallet-web/actions/runs/3884518531/jobs/6627268829#step:8:39 ...was trying to look into it.

**Comment by kyranjamie** [comment]
> When I pull dev there are uncommitted yarn.lock changes for me.

I added `b5e60a8c1` to fix this, but yes see the same. Pushed another commit to fix this 🤷🏼  Such a mess when the commits hashes are off. Cannot wait to move to a linear release processes.

I'm looking into this issue again now. I thought it might've been the many packages I updated, but those changes aren't even in `main` yet, so not sure what's changed for it to start throwing errors.

Edit: there are a handful of package changes between `3.29` and `3.30`. I downgraded typescript and it fixed it, but now I cannot recreate the issue..,

**Comment by kyranjamie** [comment]
## To reset hard before merge

**Pull request merged**
