### PR TITLE
chore: add wallet user survey, adjust styling

### PR DESCRIPTION
**Pull request by fabric-8**
> Try out Leather build f389ecc — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8536775571), [Test report](https://leather-wallet.github.io/playwright-reports/chore/user-survey-message), [Storybook](https://chore-user-survey-message--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=chore/user-survey-message)

Adds user survey while tweaking alignments / styling of `in-app-message-item.tsx`

**Would be great if we could hide this during onboarding as we don't want to target users who are just installing / onboarding, but depends on the est. effort**

The component generally looks a bit dated and due to be refactored, however that's a bit beyond my horizon. So I focussed to make things look right without performing major refactors.

CleanShot 2024-04-03 at 00 56 10@2x

CleanShot 2024-04-03 at 00 56 29@2x

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]
🚀

**Comment by fbwoolf** [comment]
Once this is merged, and you rebase on it, the test here will pass: https://github.com/leather-wallet/extension/pull/5157

**Review by kyranjamie — APPROVED** [review]
Very happy to see a non-dev modify the config ✨ 

Unless changed, this used to only show on home screen anyway, so think we're good.

Happy to make changes to this to improve it, make it more useful. It should be versatile enough to cover all simple banner use cases, without publishing changes.

**Comment by fabric-8** [comment]
@kyranjamie When testing this locally it was showing up during onboarding as well — Is the behaviour expected to be different once in actual prod environment?

**Comment by kyranjamie** [comment]
> @kyranjamie When testing this locally it was showing up during onboarding as well — Is the behaviour expected to be different once in actual prod environment? 

No, that sounds like a regression

**Comment by fabric-8** [comment]
@kyranjamie Thank you 🚀❤️

**Pull request merged**
