### PR TITLE
Release/clever agnesi

### PR DESCRIPTION
**Pull request by edu-stx**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/3361203614).

Releases:
- [refactor: broadcast fn](https://github.com/hirosystems/stacks-wallet-web/commit/07e43627f29dd4efb954c0f20a548f922b009f95)
- [fix: disable input on pw field when loading](https://github.com/hirosystems/stacks-wallet-web/commit/9e26a457cb50a397002648243d889655a6c9f93a)
- [fix: tooltip label](https://github.com/hirosystems/stacks-wallet-web/commit/ff587cd6d56075a69688f5c1a728285bd06ccb33)
- [fix: parsing invalid punycode](https://github.com/hirosystems/stacks-wallet-web/commit/18f59fa1fb5b90a32f696338bbdf7aef0beaee6b)
- [fix: add analytics events to local log](https://github.com/hirosystems/stacks-wallet-web/pull/2771/commits/b0bfb9ad022dcac450ff76023a4b72d899aa905c)

Todo: 
- [x] QA on Chrome
- [x] QA on Firefox

### CODE REVIEW

**Comment by fbwoolf** [comment]
Did you possibly not pull dev first with the merge main commit before branching off here? I think this will create duplicate commits on dev for those merge commits?

**Comment by edu-stx** [comment]
Is it better now? What I just did,

1. Check out dev
2. Merge master into dev
3. Checkout release branch on tip of dev

Now that dev has an extra merge commit on my local, should I push dev to GH?

**Comment by fbwoolf** [comment]
> Is it better now? What I just did,
> 
> 1. Check out dev
> 2. Merge master into dev
> 3. Checkout release branch on tip of dev
> 
> Now that dev has an extra merge commit on my local, should I push dev to GH?

Yep, that is typically how we do it. 👍

**Comment by edu-stx** [comment]
Great, will push dev, yet will wait for Monday for the release.

**Review by kyranjamie — APPROVED** [review]

**Review by fbwoolf — APPROVED** [review]

**Pull request merged**
