### PR TITLE
fix: brc-20 tokens breaking ledger

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5152163467).

**Hotfix**

This PR fixes ledger breaking bc we added brc-20 tokens to the asset list for sending.

### CODE REVIEW

**Comment by fbwoolf** [comment]
@alter-eggo hoping you can review this in your AM and merge it into main to release it as a hotfix.

**Review by alter-eggo — DISMISSED** [review]

**Review by alter-eggo — APPROVED** [review]

**Comment by markmhendrickson** [comment]
I'll QA with my Ledger device now

**Comment by markmhendrickson** [comment]
Is there any test(s) we can put in place for this scenario to prevent a regression in the future? If so, let's create separate issue(s).

**Comment by alter-eggo** [comment]
not sure if we can test ledger scenarios (automatically)

**Comment by markmhendrickson** [comment]
I was just able to send STX successfully with this build and Ledger device:

Screenshot 2023-06-02 at 09 53 20

**Pull request merged**
