### PR TITLE
fix: localhost not being supported

### LINKED ISSUE #1575: Fix support for StacksRegtest
Hey guys: 

I was trying to run a contract call by 'openContractCall' like this:
No matter I set the param to **StacksTestnet** or **StacksRegtest**, the popup window will always point to **testnet**.

I had a look at stacks-wallet-web source code, and I found there is no support for StacksRegtest yet, 
only **StacksMainnet** and **StacksTestnet**. 

Screen Shot 2021-08-12 at 10 16 27 PM

Hope the new version will support StacksRegtest soon, cuz the testnet is very slow now.

### LINKED ISSUE #1590: Fix support for StacksMocknet
I'm triggering a contract call from a react app to hiro wallet.
```
let mocknet = new StacksMocknet();
const options = {
  network: mocknet,
  contractAddress: stxcontractaddres,
  contractName: 'stxswap_v2',
  functionName: 'lockStx',
  functionArgs,
  appDetails: {
    name: 'stxswap',
    icon: window.location.origin + './favicon.ico',
  },
  postConditions,
  onFinish: data => {
    console.log('Stacks Transaction:', data.stacksTransaction);
  },
};
console.log("options: ", options);
await openContractCall(options);
```

I confirm it's set correctly in the browser console as below:
> options:
...
 network: StacksMocknet
_coreApiUrl: "http://localhost:3999"

wallet is giving an error because it's trying to fetch the contract from testnet
image

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1158817555).

Closes #1590

This should fix #1590, allowing users to request that the transaction signing points to local testnet.

One oversight of the changes in https://github.com/blockstack/stacks.js/pull/1044 was where `coreApiUrl` was made a getter method of the `StacksNetwork` class. This wouldn't be an issue if the object wasn't serialised/deserialised, which it is.
Thus, the private field, `_coreApiUrl` was serialised, not `coreApiUrl`.

This change adds a helper method that looks for both properties, which allows the url matcher to work properly.

cc/ @grahamulator @pseudozach

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Comment by Eshwari007** [comment]
@kyranjamie Is there any specific user acceptance criteria you want me to take a look at in this specific PR?

**Comment by markmhendrickson** [comment]
Does this resolve https://github.com/blockstack/stacks-wallet-web/issues/1575 and https://github.com/blockstack/connect/issues/160 as well?

**Comment by kyranjamie** [comment]
> Does this resolve #1575 and blockstack/connect#160 as well?

Yes, it should. I've also opened a PR in stacks.js to fix it at source https://github.com/blockstack/stacks.js/pull/1090, as well. Though only this PR is needed to fix before this is released.

**Comment by kyranjamie** [comment]
@Eshwari007 when the pending CI job is finished, you'll find new debugger options to QA this bug fix

**Pull request merged**
