### PR TITLE
Release/monday christmas

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out Leather build 48af27a — [Extension build](https://github.com/leather-io/extension/actions/runs/12468935718), [Test report](https://leather-io.github.io/playwright-reports/release/monday-christmas), [Storybook](https://release/monday-christmas--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=release/monday-christmas)

🎅🏼

This release adds @alexp3y's SIp10 balance work, and the granular UTXO handling work I've done.

### CODE REVIEW

**Review by alter-eggo — APPROVED** [review]
tested and lgtm

**Comment by fbwoolf** [comment]
@kyranjamie posted in Slack too, not sure if you know this is happening here?


https://github.com/user-attachments/assets/36bbf38e-c5a5-4581-b1e7-60f2fde18705

**Review by fbwoolf — CHANGES_REQUESTED** [review]
I don't think this should be released with that UI bug?

**Review by fbwoolf — APPROVED** [review]
Tested again, looks good now. 👍

**Pull request merged**
