### PR TITLE
fix: new tab send form nonce and scroll

### LINKED ISSUE #2453: Ledger: User cannot scroll down or see anything on the preview screen
PR:refs/pull/2242/merge
The user is stuck at the screen below and cannot scroll to  see any of the data 

bug1

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2520901090).

This fixes the initial value for nonce not being set when launching the send form in a new tab for ledger. It also fixes not being able to scroll in full page to view all tx details.

cc/ @kyranjamie

### CODE REVIEW

**Comment by fbwoolf** [comment]
@kyranjamie this needs to be merged into the ledger branch to fix a few issues.

EDIT: Looks like I need to rebase it now though.

**Comment by kyranjamie** [comment]
I can do this @fbwoolf

**Comment by kyranjamie** [comment]
Adding `overflowY="scroll"` doesn't work well, though. If you have a mouse enabled, _it will always show_

image

**Comment by fbwoolf** [comment]
> Adding `overflowY="scroll"` doesn't work well, though. If you have a mouse enabled, _it will always show_
> 
I'm not sure I get the image, wouldn't we want the scroll in that case? What is the best way to fix it then?

**Comment by kyranjamie** [comment]
A scroll within a scroll is a pretty crappy UX. 

Will have a play with it, we can for example, disable the outer scroll, and put the scroll inset within the entire modal.

**Comment by kyranjamie** [comment]
Fixing the emotion setup introduced 2 type errors, hence the `as any`. These issues reside in `@stacks/ui`, so this is an easy fix for now.

aa08abc ensures there are never double scroll bars, and that overflowed content within a drawer container can still be accessed.

**Comment by fbwoolf** [comment]
@kyranjamie commenting here bc not sure where to ask, but do we want the header with the close button to stay static during scrolling? This image is when I've scrolled to see all the tx details. I believe the header used to stay in place?

Screen Shot 2022-06-21 at 11 41 26 AM

**Pull request merged**
