### PR TITLE
fix: tx request padding

### LINKED ISSUE #2391: Style: Transaction UI horizontal padding disappears at wider window size
Repros in both Chrome and Firefox

I open a transaction using `openContractCall` in Stacks JS, a transaction window appears from the wallet extension. If I make this window wider then the horizontal padding disappears and the content ends up right against the edges, which I don't think is desirable. 

Is this intended/expected?

https://user-images.githubusercontent.com/1711350/165582555-11b40242-7de9-4662-8492-7a341261f02e.mov

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2264405942).

This PR fixes padding on the choose account and tx request center popup.

Redoing for: https://github.com/hirosystems/stacks-wallet-web/pull/2392

Screen Shot 2022-05-02 at 4 12 23 PM

Screen Shot 2022-05-02 at 4 12 39 PM

cc/ @kyranjamie @fbwoolf @beguene @He1DAr

### CODE REVIEW

**Comment by beguene** [comment]
Thanks @fbwoolf code LGTM, but can you add the original contributor to the commit ? You could do a simple git cherry-pick for example.

**Review by beguene — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]

**Comment by fbwoolf** [comment]
> can you add the original contributor to the commit ? 

Just curious why this is important if the commit wasn't complete or able to be merged?

**Comment by beguene** [comment]
@fbwoolf Just to attribute the work also to the external contributor. We welcome all contribution and we should attribute it correctly if possible.

**Comment by fbwoolf** [comment]
> @fbwoolf Just to attribute the work also to the external contributor. We welcome all contribution and we should attribute it correctly if possible.

Yep, just can't seem to cherry-pick the commit on this one ...get a `bad object` in terminal. Any other ideas to integrate it into my work when it comes from a fork?

**Comment by fbwoolf** [comment]
Also, I had to make further changes so adding the commit now seems odd considering it makes it incorrect.

**Comment by fbwoolf** [comment]
I guess one thing I could do is reopen the original PR and just work from the fork if that is preferred? I just thought it was cleaner to open a new PR but as a learning experience maybe that wasn't the best idea?

**Comment by beguene** [comment]
@fbwoolf You don't need to reopen his PR
Yes from your repo you can do the following
```
git checkout -b fix/foo
git fetch https://github.com/mcintyre94/stacks-wallet-web.git
git remote add external https://github.com/mcintyre94/stacks-wallet-web.git
git fetch external 
git cherry-pick 577a90d687c13771ed4d61fa135e1fa53db105df
```
Then you can add your commit on top.

When you are done you should remove the remote
```
git remote remove external
```

**Comment by fbwoolf** [comment]
Thanks for help @beguene! Got both commits here now.

**Comment by fbwoolf** [comment]
@timstackblock this should be ready to QA when you are available.

**Comment by Eshwari007** [comment]
Tested the PR fixes padding on the 'choose account' and 'tx request center popup.'
Test passed.Moving it out from QA

**Pull request merged**
