### PR TITLE
Refactor: Cancel STX transactions

### LINKED ISSUE #3406: Add option to cancel pending transaction
Brice: *The problem is that its not possible to cancel a transaction. Once it's reached the mempool, a miner could include it in a block. There's no way to prove whether or not the miner received your attempt to cancel it. The better option is to create a new transaction with the same nonce and a higher fee. Then it is expected that the miner will pick up the higher fee transaction instead.*

image

We can make replacing a transaction super easy. For the user it could be much like "delete transaction" By creating a STX transfer of 0.000001 to the burn address with a fee that is default set to 0.000001 STX more than the transaction being replaced. We could call it a *cancel request* rather than a *delete transaction*, as we can never be 100% certain the old isn't picked up anyway, the new transaction would have to be propagated through the network before a miner picks it up.

I think it would make it a lot easier for users to deal with troublesome transactions. Because it wouldn't require a user to understand nonces or RBF... it is handled for them.

**Lets combine this with always showing the button to increase the fee for a transaction. They should be always visible. Users do not realize the option is there if it is only shown on hover.**

This has been theorized and requested many times. It is a great help when an account has questionable transactions if something went wrong. For example a transaction to send 500 STX was send twice instead of once.

Please note that if we make sending STX very strictly #3389 possible based on available balance. I would want a "cancel request" option in case a user still succeeds in creating transactions that will remain pending until dropped. Because the regular flow may then nolonger allow sending an RBF transaction like this to unclog the wallet:
This transfer of 1 uSTX and a fee of 0.003001 STX replaces the 0.027 transfer with a fee of 0.003 STX:

image

### PR DESCRIPTION
**Pull request by Aman-zishan**
## This PR :

- implements cancelling pending stacks transactions #3406 
- Rework of #5501 & duplicate: #5520 
- Includes changes from #5500 
- Avoided code duplication 
- Reusable react components

Screenshot 2024-06-24 at 5 44 41 PM

(the layout in this video is outdated)

https://github.com/leather-wallet/extension/assets/55238388/022dd8aa-8510-4d91-afa7-6480d1dbaed8

Dropped Tx: https://explorer.hiro.so/txid/0x39dfa74f30d600cd82754030851a72763be3cdda0be9d04f6b777719400841fa?chain=testnet&api=https%3A%2F%2Fapi.nakamoto.testnet.hiro.so

Burn Tx: 
https://explorer.hiro.so/txid/0x3095aa2f935c74e858caeb948c8fd20f84a5d0e9d4f4713685cb0d0c8ed2cecb?chain=testnet&api=https%3A%2F%2Fapi.nakamoto.testnet.hiro.so

## Summary by CodeRabbit

- **New Features**
    - Introduced functionality to cancel and increase fees for transactions with a new dialog interface.
    - Added a component to display a cancel transaction dialog.
    - Added a component to display an increase fees dialog for transactions.
    - Implemented new buttons for transaction actions (increase fee, cancel) in the transaction item UI.

- **Improvements**
    - Enhanced transaction action handling with a map and new icon buttons.
    - Updated the UI to show action buttons for canceling and increasing fees on transactions.

- **Bug Fixes**
    - Improved transaction cancellation and fee increase handling with clear success messages.

### CODE REVIEW

**Comment by 314159265359879** [comment]
Thanks so much for taking this on @Aman-zishan. I see you also addressed some other minor issues from the first version, such as missing space and shortening the text. 

I like how you load the minimum fee that can replace the transaction by default and then allow the user to change that. 

I think the "x" in front of cancel could be a bit smaller, the same height as the >> symbol in front of "increase fee." I would also prefer to see it in the same color as the >> symbol. The red color is reserved for errors; we like to use red sparingly.

**Comment by Aman-zishan** [comment]
> Thanks so much for taking this on @Aman-zishan. I see you also addressed some other minor issues from the first version, such as missing space and shortening the text.
> 
> I like how you load the minimum fee that can replace the transaction by default and then allow the user to change that.
> 
> I think the "x" in front of cancel could be a bit smaller, the same height as the >> symbol in front of "increase fee." I would also prefer to see it in the same color as the >> symbol. The red color is reserved for errors; we like to use red sparingly.

@314159265359879 

Screenshot 2024-06-13 at 8 54 59 PM

 Done, i had set both icons to be the same variant "small", i think the SVG of `CloseIcon` is bigger than the other one. So i am overriding the height to reduce size.

**Comment by pete-watters** [comment]
Thanks @Aman-zishan . We value your work and will check it soon and provide feedback

**Comment by Aman-zishan** [comment]
@pete-watters Rebased and addressed the review comments.

**Comment by markmhendrickson** [comment]
@Aman-zishan can you add integration tests as well? 🙏  @kyranjamie can provide guidance

**Comment by Aman-zishan** [comment]
> @Aman-zishan can you add integration tests as well? 🙏 @kyranjamie can provide guidance

Sure, i will work on that 

@kyranjamie 

I was wondering if there are some mock functions for transaction RBF handling existing in the codebase so that i can write the integration test on a controlled environment, i think integration test for increase fee is very similar to cancel so i will try to include both in this PR

**Comment by Aman-zishan** [comment]
@markmhendrickson Addressed the change requests from #5536 discussions and rebased to latest. There is an issue with the icons where the close icon appears to be bigger compared to others and i couldn't find the exact icons as seen in the mock ups by @mica000 ; i have asked @pete-watters for guidance on the same.

**Comment by alter-eggo** [comment]
close in favor of https://github.com/leather-io/extension/pull/5920
@Aman-zishan thanks a lot for your great work on this

**Pull request closed without merging**
