### PR TITLE
Stacks 2.0 onboarding flow for hosted version

### PR DESCRIPTION
**Pull request by hstove**
> [Download the latest builds](https://github.com/blockstack/ux/actions/runs/461176001).

This PR implements the functionality described in #672 . A bunch of code from `connect-ui` was deleted, as it's no longer necessary.

The big change here is that users of the hosted version will go through a flow similar to the "installed" flow for the extension, except that there is an additional username/password step before going back to the app.

To test this, just use the testnet demo app for this PR. Don't have the extension installed.

### CODE REVIEW

**Comment by markmhendrickson** [comment]
In Firefox, I'm getting a popup warning when trying to "Sign in" with the demo app having installed this build of the extension. I would expect no warning but rather the extension to handle it:

image

**Comment by markmhendrickson** [comment]
Also the Firefox intro modal says "Chrome" above the button:

image

**Comment by markmhendrickson** [comment]
We can start handing the user off to https://www.blockstack.org/install from here for now, regardless of whether the user clicks the intro modal button from a supported or non-supported browser. The page will get updated with https://github.com/blockstack/blockstack.org/issues/1173.

Screen Shot 2021-01-04 at 14 13 42

Screen Shot 2021-01-04 at 14 13 51

For the hosted wallet path, though, can we pass a parameter for the app origin and send them back to it once they click all the way through?

**Comment by hstove** [comment]
> In Firefox, I'm getting a popup warning when trying to "Sign in" with the demo app having installed this build of the extension

Thanks @markmhx , this seems tangential though, maybe a different issue? Unfortunately this has been the behavior of the FF extension since forever. It requires some refactoring to get around that - we're re-using some a lot of the same code as the hosted flow, whereas more custom popup logic for the extension would fix it.

**Comment by hstove** [comment]
Closing this - the same code is in #748, but with a cleaner merge, fixed tests, etc.

**Pull request closed without merging**
