### PR TITLE
chore: update stx avatar

### PR DESCRIPTION
**Pull request by fabric-8**
> Try out Leather build dc14f8a — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8610932758), [Test report](https://leather-wallet.github.io/playwright-reports/chore/update-stx-avatar), [Storybook](https://chore-update-stx-avatar--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=chore/update-stx-avatar)

Updates to the latest stx avatar/logo according to the [updated brand guidelines](https://www.figma.com/file/afyAaHa2vGCR0KU1BHiske/Stacks-Brand-2024?type=design&node-id=280%3A698&mode=design&t=EA6jtoHSGQvN778P-1)

CleanShot 2024-04-08 at 22 29 23@2x

### CODE REVIEW

**Review by kyranjamie — COMMENTED** [review]
See errors in file changes, dupe prop 
image

**Comment by kyranjamie** [comment]
When making fixes to your commits, I recommend use of the [`--amend` flag](https://www.atlassian.com/git/tutorials/rewriting-history), to change the existing commit, rather than adding new, unimportant ones.

**Comment by fabric-8** [comment]
@kyranjamie Noted, will do so in the future

**Comment by fbwoolf** [comment]
@fabric-8 if you run `git log` and copy the commit before yours on the branch, then run `get rebase -i <commit>` ...you should be able to squash all these into one commit.

**Comment by fabric-8** [comment]
Squashed all unnecessary commits into one ✓

**Review by kyranjamie — APPROVED** [review]
Thanks @fabric-8 !

**Pull request merged**
