### PR TITLE
Release/2022 07 04 enormous elephant

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2656038269).

Contents:

- Enabled Ledger feature flag
- Several CI fixes by @kyranjamie 
- https://github.com/hirosystems/stacks-wallet-web/issues/2345
- https://github.com/hirosystems/stacks-wallet-web/issues/2507
- https://github.com/hirosystems/stacks-wallet-web/pull/2516 thx @luciorubeens 
- https://github.com/hirosystems/stacks-wallet-web/issues/2517 thx @luciorubeens

cc/ @kyranjamie @fbwoolf

### CODE REVIEW

**Comment by fbwoolf** [comment]
@kyranjamie I ran thru and tested this, seems good on my end. Maybe you want to run thru it and merge in your AM?

*Didn't you mention something we needed to update in the code before releasing? Something with Zondax version maybe?

**Comment by kyranjamie** [comment]
Thanks @fbwoolf—

Yeah would be better to release tomorrow morning, is a bit late for me. The version we have now is behind the current, but also fine, as it supports jwt (even though .7 is latest)

https://github.com/hirosystems/stacks-wallet-web/blob/427e592bef3cdd82c4bb63362efe1ee8a5cc36f0/src/app/features/ledger/ledger-utils.ts#L187

**Comment by fbwoolf** [comment]
Hitting this on lock screen when signing out from software wallet...

Screen Shot 2022-07-04 at 2 41 30 PM

EDIT: This has been resolved.

**Comment by fbwoolf** [comment]
Found this today testing the release, after confirming a transaction the modal isn't closing and returning to the app. Will try to fix today.

Screen Shot 2022-07-09 at 1 06 23 PM

**Comment by fbwoolf** [comment]
It looks like the code is `navigate(RouteUrls.Home);` ...I don't think that is what we want though ...we want the modal to close?

EDIT: This has been fixed.

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
