### PR TITLE
Release/wednesday

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/4504184730).

Wednesday release

### CODE REVIEW

**Review by edu-stx — DISMISSED** [review]

**Review by fbwoolf — APPROVED** [review]

**Comment by fbwoolf** [comment]
Name suggests I should be releasing this today? 🤔

**Comment by fbwoolf** [comment]
~~DO NOT RELEASE THIS UNTIL I FIX SOME BUGS ON DEV:~~

https://github.com/hirosystems/wallet/pull/3477

EDIT: Merged and included here.

**Comment by fbwoolf** [comment]
Not sure about releasing these removed conditionals @edu-stx, one introduced a bug. Did you check the others?

**Comment by fbwoolf** [comment]
Should this be merged in here before we release? It might solve some other possible bugs from ft/nft conditionals being removed: https://github.com/hirosystems/wallet/pull/3466

**Review by fbwoolf — DISMISSED** [review]
~~Bugs are present here until other work is merged to fix.~~

Seems fixed in latest build, but please test tom morning. I think it would be best to include the changes in https://github.com/hirosystems/wallet/pull/3466 before releasing if possible.

**Review by edu-stx — DISMISSED** [review]
Tested it again, no errors thrown. Had a deeper look at the code related to the conditional changes and seems to be ok

**Comment by fbwoolf** [comment]
> Tested it again, no errors thrown. Had a deeper look at the code related to the conditional changes and seems to be ok

Thx @edu-stx, that lint rule makes me nervous, haha.

**Review by fbwoolf — DISMISSED** [review]

**Review by fbwoolf — APPROVED** [review]

**Pull request merged**
