### PR TITLE
fix: onboarding test

### PR DESCRIPTION
**Pull request by alter-eggo**
There is some problem with validation on set password step in testing process.
I'm not sure why but [auto-waiting](https://playwright.dev/docs/actionability) not working in this case

### CODE REVIEW

**Comment by alter-eggo** [comment]
personally I don't like the solution. wait for timeout is not a good practice. @fbwoolf @kyranjamie may be you will have some better ideas here

**Comment by fbwoolf** [comment]
> personally I don't like the solution. wait for timeout is not a good practice. @fbwoolf @kyranjamie may be you will have some better ideas here

Thanks for looking into it, I personally haven't ever found a better solution and don't understand myself why the auto-wait doesn't work at times. I'll look into it today, but this might be a good solution for now.

**Review by fbwoolf — APPROVED** [review]

**Comment by kyranjamie** [comment]
@alter-eggo @fbwoolf indeed `waitForTimeout` is best avoided. 

In this instance, I wonder if you tried:

```ts
const button = await this.page.getByTestId(OnboardingSelectors.SetPasswordBtn);
await button.isEnabled();
await button.click();
```

?

**Comment by alter-eggo** [comment]
@kyranjamie  yes, I tried

**Pull request merged**
