### PR TITLE
Release - Signer Fix

### LINKED ISSUE #5266: "Unexpected Application Error" after updating Chrome
image

After updating my Chrome browser, Leather extension doesn't work well.

I uploaded the screenshot.

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out Leather build b3109ed — [Extension build](https://github.com/leather-wallet/extension/actions/runs/8740725802), [Test report](https://leather-wallet.github.io/playwright-reports/release/signer-fix), [Storybook](https://release-signer-fix--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=release/signer-fix)

This release contains fixes for:

- https://github.com/leather-wallet/extension/issues/5243
- https://github.com/leather-wallet/extension/issues/5255
- https://github.com/leather-wallet/extension/issues/5251
- https://github.com/leather-wallet/extension/issues/5246
- https://github.com/leather-wallet/extension/issues/5207
- https://github.com/leather-wallet/extension/issues/5250

### CODE REVIEW

**Comment by fbwoolf** [comment]
Why would we release this w/out Runes included?

**Comment by pete-watters** [comment]
> Why would we release this w/out Runes included?

I've added the Runes UI work https://github.com/leather-wallet/extension/issues/5246 . I didn't want to merge your PR again. 

If there is more stuff to add we can before releasing. Maybe this PR? https://github.com/leather-wallet/extension/pull/5179

**Comment by pete-watters** [comment]
We will need to add https://github.com/leather-wallet/extension/pull/5262 also

**Comment by fbwoolf** [comment]
> If there is more stuff to add we can before releasing. Maybe this PR? #5179

We can leave https://github.com/leather-wallet/extension/pull/5179 for the next release. I am still finishing some refactoring there.

**Review by fbwoolf — APPROVED** [review]

**Comment by fbwoolf** [comment]
I forgot to add the default Runes symbol to my last PR. I will get the change merged then update the release branch.

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
