### PR TITLE
test: new sbtc network

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out Leather build 22aa41b — [Extension build](https://github.com/leather-io/extension/actions/runs/11957426087), [Test report](https://leather-io.github.io/playwright-reports/demo-new-network), [Storybook](https://demo-new-network--65982789c7e2278518f189e7.chromatic.com), [Chromatic](https://www.chromatic.com/library?appId=65982789c7e2278518f189e7&branch=demo-new-network)

This PR generates a build with the sBTC Testnet network, pointing to Stacks testnet and generating regtests addresses for https://beta.sbtc-mempool.tech/api/proxy

This needs to be modified in monorepo, but here for testing purposes

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Review by camerow — APPROVED** [review]

**Comment by camerow** [comment]
Anything specific I can help test here?

**Comment by setbern** [comment]
Still running into Leather validation issue for `sbtcTestnet`

This is the code that i'm running 
```ts
 const sendParams = {
          recipients: [
            {
              address: p2trAddress,
              amount: `${amount}`,
            },
          ],
          network: process.env.NEXT_PUBLIC_WALLET_NETWORK || "sbtcTestnet",
        };
```
 process.env.NEXT_PUBLIC_WALLET_NETWORK is `sbtcTestnet`
 
p2trAddress = bcrt1pzxz00vdnc8j4rz6u9axp6jmh60f8v7t8zkmwzm4x3899fvvl78nseyz7r2

response "Validation error: Address is for incorrect network at "recipients""

**Comment by kyranjamie** [comment]
@setbern this is a different validation error, fixing now

**Comment by setbern** [comment]
@kyranjamie  If i comment out the following it works (probably involves what you pointed out)

```ts
export const rpcSendTransferParamsSchema = z
  .object({
    account: accountSchema.optional(),
    // works if i comment out the line below
    //network: defaultNetworksSchema.optional(),
    recipients: z
      .array(
        z.object({
          address: z.string(),
          amount: z.string().refine(value => checkIfDigitsOnly(value), {
            message: 'Sat denominated amounts only',
          }),
        })
      )
      .nonempty()
      .refine(
        recipients => {
          const inferredNetworksByAddress = recipients.map(({ address }) =>
            getNetworkTypeFromAddress(address)
          );
          return uniqueArray(inferredNetworksByAddress).length === 1;
        },
        { message: 'Cannot tranfer to addresses of different networks', path: ['recipients'] }
      ),
  })
  .refine(
    ({ network, recipients }) => {
      const addressNetworks = recipients.map(recipient =>
        btcAddressNetworkValidator(network as BitcoinNetworkModes).isValidSync(recipient.address)
      );

      return !addressNetworks.some(val => val === false);
    },
    { message: FormErrorMessages.IncorrectNetworkAddress, path: ['recipients'] }
  );
  ```

**Comment by kyranjamie** [comment]
@setbern fixed it, there was an illegal type cast here

```ts
btcAddressNetworkValidator(network as BitcoinNetworkModes) // was not BitcoinNetworkModes
```

**Comment by aldur** [comment]
Tested this as well and confirming it works on my side too, thank you!

**Pull request merged**
