### PR TITLE
hiro <> dlc.link implementation [fixed commit messages]

### LINKED ISSUE #3541: Integrate DLC signing into Hiro Wallet
---
### Integrate DLC signing into Hiro Wallet
In order to use DLCs, Bitcoin wallets need to import a library which can sign and manage DLC contracts.

---

A DLC primarily consists of two Bitcoin transactions, a _funding tx_ and a _Contract Execution Transaction (CET)_. The DLC library from DLC.Link provides JS interface for building and managing the DLC contracts, and doing the signatures required. See below for more information about how DLCs function and why unique code is needed for them.

#### Tasks
* Add the dlc library, and instantiate the DLC manager object with wallet internal pieces (blockchain access, btc keys, etc)
* Build DLC signing flow into the architecture. Main actions: Sign / Accept DLC, navigate to DLCs page button, view existing DLCs.
* Build UX/UI components / pages matching the existing style. Main pages: Sign DLC, DLC details, etc.

#### Additional Reading
* Additional reading about dlc-lib - https://docs.google.com/document/d/1v5E17KxZaL5rXTvbyJkm5osR5-cNhYGlVcKdSCuK4j0
* Additional reading about DLC.Link: https://www.dlc.link/blog
* Additional reading about DLCs: https://github.com/discreetlogcontracts/dlcspecs

### PR DESCRIPTION
**Pull request by Polybius93**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5609504424).

### CODE REVIEW

**Review by fbwoolf — COMMENTED** [review]
Lgtm! Thanks @Polybius93 for making all the requested changes. Looking fwd to the demo tomorrow. 👍

**Review by kyranjamie — APPROVED** [review]
Great work @Polybius93, we'll aim to get this merged this week

**Comment by kyranjamie** [comment]
I've audited the wasm code and LGTM. Good to merge after successful MV3 release.

**Comment by markmhendrickson** [comment]
@kyranjamie Want to prepare a release of this one for today?

**Comment by pete-watters** [comment]
@Polybius93 : I am updating the popup UI for this.  Can you please help me understand how I can trigger this contract request popup to make sure it looks OK? 

Is there a way to call the RPC method from the console or to test DLC link in general?

**Comment by fbwoolf** [comment]
> 
> Is there a way to call the RPC method from the console or to test DLC link in general?

You should just be able to run the test-app and call the rpc method in the console using `window.LeatherProvider.request('acceptBitcoinContractOffer', params)`. Look in `/tests/specs/bitcoin-contract-offer-accept/bitcoin-contract-offer-accept.spec.ts` for what you can use as params.

**Comment by pete-watters** [comment]
> > Is there a way to call the RPC method from the console or to test DLC link in general?
> 
> You should just be able to run the test-app and call the rpc method in the console using `window.LeatherProvider.request('acceptBitcoinContractOffer', params)`. Look in `/tests/specs/bitcoin-contract-offer-accept/bitcoin-contract-offer-accept.spec.ts` for what you can use as params.

I tried doing that earlier, copying the code from the test but I get the error:
`'The provided parameters are not valid.'` 

I must be missing something if the tests are passing. I can try again

**Pull request merged**
