### PR TITLE
Release/6.11.1

### PR DESCRIPTION
**Pull request by pete-watters**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/6625368424).

This release contains:
- #4170 
- #4028 
- #4086 
- #4374 
- #4334 
- #1234 
- #1232 
- #1235 
- #152 
- #153 
- #150 
- #4281 
- #4388

### CODE REVIEW

**Comment by pete-watters** [comment]
I named it `6.11.1` but I'm not sure if that will be the version increment. 

I think we should come up with a system to name the releases the same as the tag and version increment. I used GitFlow CLI for this in the past: https://github.com/nvie/gitflow

**Review by kyranjamie — APPROVED** [review]

**Comment by kyranjamie** [comment]
> I think we should come up with a system to name the releases the same as the tag and version increment. I used GitFlow CLI for this in the past: https://github.com/nvie/gitflow 

Re your point, this is a limitation of semantic-release. The idea is you don't need to know the version, but it's limiting imo. [There's an issue asking for a feature that allows you to know ahead of time what version it'll use](https://github.com/semantic-release/semantic-release/issues/753), so we could do just this.

**Comment by kyranjamie** [comment]
I hope the merge back works better this time 🙏🏼

**Comment by pete-watters** [comment]
> > I think we should come up with a system to name the releases the same as the tag and version increment. I used GitFlow CLI for this in the past: https://github.com/nvie/gitflow
> 
> Re your point, this is a limitation of semantic-release. The idea is you don't need to know the version, but it's limiting imo. [There's an issue asking for a feature that allows you to know ahead of time what version it'll use](https://github.com/semantic-release/semantic-release/issues/753), so we could do just this.

Thanks 👍 I'll take a look and see if I can use `dry-run` or else a plugin to do this. There is a fork we could potentially use also https://github.com/semantic-release-plus/semantic-release-plus 

I take it that `semantic-release` gives us some benefits and we want to keep using it. It's used by `nx-release` also which I will test run for the mono repo - https://youtu.be/NQHk7HhP1Uo?feature=shared

**Pull request merged**
