### PR TITLE
fix(psbt): dynamic validation of sighash type

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5348881203).

Added additional validation that if sign at index is defined, allowedSighash is required

### CODE REVIEW

**Comment by fbwoolf** [comment]
btc-signer uses a default sighash for signing an index, `SignatureHash.ALL`: https://github.com/paulmillr/scure-btc-signer/blob/91b37a5e2d5bc372d079f399efa552f4eb132cb7/index.ts#L2243

**Comment by kyranjamie** [comment]
@fbwoolf logic is https://github.com/hirosystems/wallet/blob/519cfd2b8a65ef9cae633c49363bfb4d3b0b1a50/src/app/pages/rpc-sign-psbt/rpc-sign-psbt.tsx#L52-L55

is this not correct?

**Comment by fbwoolf** [comment]
> 
> is this not correct?

Not really, `allowedSighash` is optional in our params and in the btc-signer lib.

**Comment by fbwoolf** [comment]
@kyranjamie I think my commit here is what we want?

**Comment by kyranjamie** [comment]
Yep LGTM @fbwoolf

**Review by fbwoolf — APPROVED** [review]
Tested and seems to be working.

**Pull request merged**
