### PR TITLE
Release

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1508055712).

PR for release.

cc/ @kyranjamie @beguene
cc/ @Eshwari007 @timstackblock

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]

**Comment by fbwoolf** [comment]
@kyranjamie this was pointed out, not sure how I missed this and it passed through everything but the network is hardcoded to testnet in the query. That will need to be fixed and added to this release. 😬 

https://github.com/hirosystems/stacks-wallet-web/blob/b2dc58e5a36fc52920126cf88ad7623336d7bd2b/src/query/fees/fees.query.ts#L20

**Comment by fbwoolf** [comment]
PR to add to this: https://github.com/hirosystems/stacks-wallet-web/pull/1998

**Comment by fbwoolf** [comment]
I think I am stuck not being able to release this w/out the right permissions to fix these conflicts.

**Comment by kyranjamie** [comment]
@fbwoolf just pushed a merge commit

**Comment by fbwoolf** [comment]
Ok, great, I can't seem to do that so you must have different permissions.

**Pull request merged**
