### PR TITLE
refactor: mask secret key sign in

### LINKED ISSUE #3689: Mask Secret Key entry during sign in by default
Providing an option to reveal the value if desired, to protect from onlookers / cameras in public places.

Similar to https://github.com/hirosystems/wallet/issues/3560

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5292600310).

Clone of: https://github.com/hirosystems/wallet/pull/3734

Tested and works well now.

Also, noticed/fixed a bug here in routing from the set password page. It was always going back to `BackUpSecretKeyPage` which isn't desired if onboarding with an existing key.

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]

**Comment by kyranjamie** [comment]
Pity there aren't easier ways to mask than having to parse the input like this. Alternate simpler technique https://jsfiddle.net/0z6tqgxm/22/

**Comment by fbwoolf** [comment]
> Pity there aren't easier ways to mask than having to parse the input like this. Alternate simpler technique https://jsfiddle.net/0z6tqgxm/22/

This link isn't loading JS code for me. 🤔

**Comment by kyranjamie** [comment]
@fbwoolf 
image

**Comment by fbwoolf** [comment]
> 

O, sorry, I see ...should we do that instead here?

**Comment by fbwoolf** [comment]
Ended up merging this bc I felt it matched our password input on the next step. We can refactor it in another PR if feel this implementation is too complicated.

**Pull request merged**
