### PR TITLE
feat: add stacks multisig support, closes #3889

### LINKED ISSUE #3889: Add multisignature option for Stacks transactions
We're building the first native multi-sig wallet for Stacks, and for that, we really miss that functionality for signing multi-signature transactions
there're functions like
`openContractDeploy`
`openContractCall`
`openStxTokenTransfer`
But for now, it can't work with multisig transactions, which is essential if we want to connect with the Hiro wallet from our frontend UI
All existing libraries for Stacks wallet connection lack this feature - [`micro-stacks`](https://micro-stacks.dev/docs/overview) and [`stacks.js`](https://docs.hiro.so/stacks.js/overview)

Related issue https://github.com/hirosystems/wallet/issues/1454
Related SIP for the signing order problem https://github.com/stacksgov/sips/pull/139
Related code for multi-sig transaction flow using @stacks js library https://github.com/hirosystems/stacks.js/issues/1487
PR for stacks blockchain for the SIP above https://github.com/stacks-network/stacks-blockchain/pull/3710

Native multisig transactions still have a problem described in the proposal, but the overall flow can already be established, therefore we're trying to integrate our solution with Hiro

### PR DESCRIPTION
**Pull request by kyranjamie**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/6456329893).

Copy of @fess-v's PR

### CODE REVIEW

**Comment by fess-v** [comment]
@kyranjamie fixed it in my previous PR branch, seems like lint:fix or lint:prettier:fix do some changes that break types logic :(
like it was in such files as `bns.utils.ts`

**Comment by markmhendrickson** [comment]
@kyranjamie is this ready to release assuming we merge in the latest from the previous branch?

**Review by fbwoolf — APPROVED** [review]
Lgtm, should the promise warnings be addressed here?

**Review by alter-eggo — APPROVED** [review]

**Review by pete-watters — APPROVED** [review]

**Comment by kyranjamie** [comment]
> Lgtm, should the promise warnings be addressed here?

Don't think these were introduced here so will just merge

**Pull request merged**
