### PR TITLE
feat: mask secret key during sign in

### LINKED ISSUE #3689: Mask Secret Key entry during sign in by default
Providing an option to reveal the value if desired, to protect from onlookers / cameras in public places.

Similar to https://github.com/hirosystems/wallet/issues/3560

### PR DESCRIPTION
**Pull request by lakshdhamija**
resolves: #3689 

https://github.com/hirosystems/wallet/assets/1527402/b76b988c-924d-4321-aabe-024014048592

### CODE REVIEW

**Comment by fbwoolf** [comment]
@markmhx this isn't working for me, so will have to rework. Only works well on paste. If the user just starts typing, it is broken. Do we really want the key masked if a user starts typing?

Screen Shot 2023-06-01 at 9 37 29 AM

**Comment by markmhendrickson** [comment]
I presume it's best to keep masked if the user starts typing (akin to password field behavior, though with perhaps the key difference being that Secret Keys are usually much longer so harder to keep track of typing?).

Curious what @mica000 thinks

**Comment by fbwoolf** [comment]
> I presume it's best to keep masked if the user starts typing (akin to password field behavior, though with perhaps the key difference being that Secret Keys are usually much longer so harder to keep track of typing?).
> 
If so, I'll need to do some work on this after custom fees or we can ask the contributor to fix?

**Comment by markmhendrickson** [comment]
@lakshdhamija mind fixing?

**Comment by fbwoolf** [comment]
> @lakshdhamija mind fixing?

It appears I can fix this quick with the input type toggling. I'll fix in the cloned branch I have locally. @lakshdhamija no need to address here.

**Comment by Safvan-tsy** [comment]
> @markmhx this isn't working for me, so will have to rework. Only works well on paste. If the user just starts typing, it is broken. Do we really want the key masked if a user starts typing?



I have mentioned a small bug related to this in issue #3560 comments. Mentioning it here, hoping it will useful in this case

https://github.com/hirosystems/wallet/issues/3560#issuecomment-1524546986  
https://github.com/hirosystems/wallet/issues/3560#issuecomment-1524547904

**Comment by fbwoolf** [comment]
> I have mentioned a small bug related to this in issue #3560 comments. Mentioning it here, hoping it will useful in this case
> 
Thanks, I have cloned these PRs for masking the secret key and will get them merged today or early next week.

**Comment by markmhendrickson** [comment]
@fbwoolf this is ready for re-review now that @lakshdhamija has made additional changes per your previous review

**Comment by fbwoolf** [comment]
Ok, thanks, I'll retest it today.

**Comment by fbwoolf** [comment]
Closing in favor of cloned PR here: https://github.com/hirosystems/wallet/pull/3886

Thanks for the contribution! @lakshdhamija

**Pull request closed without merging**
