### PR TITLE
Add copy address btn in switch account menu (Closes #3069)

### LINKED ISSUE #3072: Add option to copy address from switch account list
[From BNS Discord:](https://discord.com/channels/1024525432403537982/1024525432952995862/1072792549594513438)

> Let's say we are in account 47, then there is a small "copy address" button next to the address.
It would be awesome and save a lot of time, when you could implement that copy address button also on the "Switch account" site. Then we could copy all addresses while staying on that tab and don't have to open every single account to be able to copy the address.

### PR DESCRIPTION
**Pull request by alter-eggo**
This pr fixes https://github.com/hirosystems/stacks-wallet-web/issues/3072
There is problem with tooltip hiding, which is fixed here: https://github.com/hirosystems/stacks-wallet-web/pull/3069

### CODE REVIEW

**Comment by markmhendrickson** [comment]
Thanks! Mind providing a short screen recording to display how the UX here works as you hover over each account?

**Comment by alter-eggo** [comment]
@markmhx sure

https://user-images.githubusercontent.com/46521087/217842673-416ddb0e-70c7-4ecf-8485-ca84b0a21db0.mov

**Comment by alter-eggo** [comment]
@markmhx sure

https://user-images.githubusercontent.com/46521087/217842673-416ddb0e-70c7-4ecf-8485-ca84b0a21db0.mov

**Comment by markmhendrickson** [comment]
This interaction may be a bit tricky given the overlapping selection areas (outside for selecting account, inside for copying address). Though it looks good enough for a first implementation and we can improve from there.

@mica000 wdyt?

**Comment by mica000** [comment]
@markmhx Agree. I can take a better look into it. For now it's good enough

**Comment by alter-eggo** [comment]
merged dev. with BTC address it looks like this:
Screenshot 2023-02-18 at 23 05 41

**Comment by alter-eggo** [comment]
close in favour of https://github.com/hirosystems/stacks-wallet-web/pull/3277

**Pull request closed without merging**
