### PR TITLE
fix: reduce send form click area

### PR DESCRIPTION
**Pull request by alter-eggo**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5199661255).

This pr reduce send form "click to focus" area, also changes validators order in btc send form

### CODE REVIEW

**Comment by alter-eggo** [comment]
https://github.com/hirosystems/wallet/assets/46521087/9568e89b-6168-4519-98e5-8662faadc652

there is one last problem with triggering validation, not sure if it possible to fix? wdyt @kyranjamie

**Comment by kyranjamie** [comment]
Will take a look @alter-eggo

**Review by kyranjamie — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]

**Comment by alter-eggo** [comment]
@mica000 can you test send max in this build pls?

**Comment by mica000** [comment]
@alter-eggo LGTM!

**Pull request merged**
