### PR TITLE
Release/2022 09 12 pumped parrot

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/3053741452).

Contents:

- https://github.com/hirosystems/stacks-wallet-web/issues/2433
- https://github.com/hirosystems/stacks-wallet-web/issues/2638
- https://github.com/hirosystems/stacks-wallet-web/issues/2644
- https://github.com/hirosystems/stacks-wallet-web/issues/2639
- https://github.com/hirosystems/stacks-wallet-web/issues/2594
- https://github.com/hirosystems/stacks-wallet-web/issues/2441
- https://github.com/hirosystems/stacks-wallet-web/issues/2645
- https://github.com/hirosystems/stacks-wallet-web/issues/2653
- https://github.com/hirosystems/stacks-wallet-web/issues/2656

cc/ @kyranjamie @fbwoolf

### CODE REVIEW

**Comment by fbwoolf** [comment]
Tested in Chrome ✅

**Comment by fbwoolf** [comment]
~~@kyranjamie seeing this with a sponsored tx in the test-app, should an error screen be shown here with your changes?~~

**Comment by fbwoolf** [comment]
Nvm, I see your changes were just with the broadcast error.

**Comment by kyranjamie** [comment]
Firefox ✅

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
