### PR TITLE
feat: stamps collectibles

### LINKED ISSUE #3589: Display Bitcoin Stamps in "Collectibles" area of home screen
In addition to displaying Ordinal inscriptions, BNS names and Stacks NFTs in the "Collectibles" area of the home screen, we should show Bitcoin Stamps as well. [See relevant code](https://github.com/hirosystems/wallet/blob/f5c8b1e3be397acb92a2e14247caf84d32e61c4f/src/app/features/collectibles/collectibles.tsx)

In theory there wouldn't have to be any UI changes aside from labeling them with "Bitcoin Stamp" and on hover omitting the "Send" button (until tackled separately):

Screenshot 2023-04-24 at 14 01 07

Screenshot 2023-04-24 at 14 01 41

Clicking the arrow on hover could take the user to a stampchain.io (e.g. https://stampchain.io/asset.html?stampNumber=18478).

This API could be used to pull data on Stamps owned by the account's Native SegWit address: https://github.com/hydren-crypto/stampchain/blob/main/documentation/api.md

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/4873865048).

This PR adds displaying Stamps under Collectibles.

Screen Shot 2023-05-02 at 4 16 21 PM

### CODE REVIEW

**Comment by fbwoolf** [comment]
~~@kyranjamie I can't figure out why these send form playwright tests would be failing on my branch, any chance bc of your sharding changes?~~ 🤔 

~~EDIT: When I run locally, it appears buttons aren't working.~~

EDIT: Nvm, must have been an api issue.

**Review by kyranjamie — COMMENTED** [review]
Looks good Fara, nice work.

Now that there's a stamps by address endpoint, can we remove the big collections query? 

Also, discussed in Monday call, is the problem of issues not being tied to releases. Please reference the issue in your commit to fix this & help police missing issue commit references when you see them.

**Comment by fbwoolf** [comment]
> Looks good Fara, nice work.
> 
> Now that there's a stamps by address endpoint, can we remove the big collections query?
> 
> Also, discussed in Monday call, is the problem of issues not being tied to releases. Please reference the issue in your commit to fix this & help police missing issue commit references when you see them.

Right, forgot, I'll add the issue # to the commit. Yeah, we can likely remove the collections query. Want me to do that here?

**Comment by fbwoolf** [comment]
Going to merge this and capture the collection refactor work in a new PR.

**Pull request merged**
