### PR TITLE
fix: Fix max width on Stacks contract UI , closes #3966

### LINKED ISSUE #3966: Fix max width on Stacks contract UI
A max width is incorrectly applied on the inner container

CleanShot 2023-07-03 at 17 19 40@2x

### PR DESCRIPTION
**Pull request by prasad5795**

### CODE REVIEW

**Comment by pete-watters** [comment]
Thanks @prasad5795 👍 

Can you please:
- sign the CLA
- squash your commits / drop `14b0fb8`

Then I'll be happy to approve and merge this

**Comment by prasad5795** [comment]
@pete-watters done

**Review by pete-watters — APPROVED** [review]
LGTM. Thanks @prasad5795 👏

**Comment by markmhendrickson** [comment]
Thanks from me as well for the contribution @prasad5795, and @pete-watters for helping review and get it merged! 💪

**Pull request merged**
