### PR TITLE
feat: use shadow-dom for connect modal

### LINKED ISSUE #378: Resolve CSS issues with introductory modal for Loopbomb
See https://test.loopbomb.com/

Reported by @radicleart

### LINKED ISSUE #456: Ensure placement of close icon within intro modal
It shows up to further to the left on http://humans.name/

### LINKED ISSUE #457: Prevent cascading hover effects in introductory modal
For example, when the cursor hovers over the button on http://humans.name/, it increases in size and changes the text color:

### PR DESCRIPTION
**Pull request by hstove**
It's rendering properly in a shadow-dom, and the modal still gets triggered correctly. However, something is off with click events. If you click anywhere, the modal hides. Need to debug further.

cc @aulneau @kyranjamie

### CODE REVIEW

**Comment by aulneau** [comment]
@hstove it closing on any click might be due to the hook we're using for on outside click, I wonder if refs break some how in shadow land?

**Comment by markmhendrickson** [comment]
@hstove is this ready for assigning reviewers? I see it's under code review but still in draft.

**Comment by hstove** [comment]
Not ready for review, yet. Still stuck on some behavior I need to debug - click events relating to the modal don't work on this PR.

**Comment by hstove** [comment]
Closing - we're using #582

**Pull request closed without merging**
