### PR TITLE
feat: upgrade @stacks package to 3.1.0

### PR DESCRIPTION
**Pull request by pradel**
Simple pr upgrading the stacks.js dependencies released as 3.1.0 today.

Linked issue https://github.com/blockstack/stacks.js/pull/1117.

cc/ @kyranjamie @fbwoolf

### CODE REVIEW

**Comment by andresgalante** [comment]
@kyranjamie How risky it'd be to do a release out of master just with the commit before the code freeze on Monday?

**Comment by kyranjamie** [comment]
I would say fairly risky without thorough QA. Unforeseen issues are the reason for the code freeze.

@pradel I know you're eager for this feature. We can share a feature build for you to test it over the holidays if this helps?

**Comment by pradel** [comment]
@kyranjamie yes please, that would be great.
When can we expect it to be released if it's not included in this version?

**Comment by kyranjamie** [comment]
Closing for https://github.com/hirosystems/stacks-wallet-web/pull/2089

**Pull request closed without merging**
