### PR TITLE
chore: rename key to avoid cache collisions

### PR DESCRIPTION
**Pull request by aulneau**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/blockstack/ux/actions/runs/1234009248).

This makes a small change so that fungible token meta data will not use the same cache key as it did in older versions, as the shape of persisted data has changed.

cc/ @aulneau @kyranjamie @fbwoolf

### CODE REVIEW

**Review by fbwoolf — APPROVED** [review]

**Review by kyranjamie — APPROVED** [review]
Could we use the action wallet version in key as well?

**Comment by aulneau** [comment]
> Could we use the action wallet version in key as well?

Do we want something like this https://github.com/blockstack/stacks-wallet-web/pull/1708/commits/078945e54e7f58f5c72395249b99bbef1cd575b4 ?

**Comment by kyranjamie** [comment]
yes, nice 👍🏼

**Comment by aulneau** [comment]
I also added it to the query client persistence: https://github.com/blockstack/stacks-wallet-web/pull/1708/commits/85c7617b59fdc503f9195cc8be7726ab49de97f7#diff-2a29b6ded1b3297189cd352577bba1694275daf0167ced108f0f51bf8a424944R21

**Pull request merged**
