### PR TITLE
fix: inscriptions on regen addresses, closes #3752

### LINKED ISSUE #3752: Ordinals not loading for some users on regenerated addresses
Possibly it is related to ordinals being on regenerated address from before March 20th such as this case:

used 4.26.0 and 4.24.2 console doesn't show relevant errors. 
image

https://discord.com/channels/1075856098269089834/1075920122314756166/1111377159261528165
image

The user thought this may have been relevant but I do not think so because the addresses were generated by Hiro https://github.com/hirosystems/wallet/issues/3297

### PR DESCRIPTION
**Pull request by alter-eggo**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/wallet/actions/runs/5333299801).

Problem was that after dynamic loading many inscriptions from one address, `offset` was not reset, and we fetched inscriptions from new addresses with old big `offset`

### CODE REVIEW

**Comment by markmhendrickson** [comment]
Let's link PRs to their issues here on the right-hand side in general (and move issue into review when ready for it) 🙏 

Screenshot 2023-06-21 at 13 07 20

**Comment by alter-eggo** [comment]
@markmhx seems we need to mention issue in description, so it (linking prs to issues) would be done automatically🤔 ?

**Comment by markmhendrickson** [comment]
Ah yea, I'm not sure if it gets linked automatically if mentioned in the issue. But if so, sgtm!

**Review by kyranjamie — APPROVED** [review]

**Comment by kyranjamie** [comment]
I think it gets linked automatically when mentioned in description, but not commit msg

**Review by fbwoolf — APPROVED** [review]

**Pull request merged**
