### PR TITLE
feat: added tests for bitcoin contract request

### PR DESCRIPTION
**Pull request by Polybius93**
> Try out this version of Leather — [download extension builds](https://github.com/leather-wallet/extension/actions/runs/6576962512).

### CODE REVIEW

**Review by kyranjamie — COMMENTED** [review]
Is the .patch file used anywhere?

**Comment by Polybius93** [comment]
> Is the .patch file used anywhere?

Nope, accidental add, removing it now

**Comment by kyranjamie** [comment]
FYI for changes like this you can use `git commit --amend` rather than creating a new commit or rebasing

image

This commit isn't compliant with our commit rules, and the `!` can trigger a major release

**Comment by Polybius93** [comment]
> FYI for changes like this you can use `git commit --amend` rather than creating a new commit or rebasing
> 
> image
> This commit isn't compliant with our commit rules, and the `!` can trigger a major release

Thank you! Yeah, usually I rebase and then these commits are squashed without this commit message.

**Comment by Polybius93** [comment]
@kyranjamie I've fixed all failing tests

**Review by kyranjamie — APPROVED** [review]

**Pull request merged**
