### PR TITLE
Release/2022 03 02 white buffalo

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/1985621544).

Content:

- https://github.com/hirosystems/stacks-wallet-web/pull/2172
- https://github.com/hirosystems/stacks-wallet-web/pull/2272
- https://github.com/hirosystems/stacks-wallet-web/pull/2288
- https://github.com/hirosystems/stacks-wallet-web/pull/2295
- Refine language around transaction signing https://github.com/hirosystems/stacks-wallet-web/commit/8c889e0173b8ce0d859b07af2c3e431618284fea

### CODE REVIEW

**Comment by fbwoolf** [comment]
If I run this branch locally I'm getting this when trying to create an account:
Screen Shot 2022-03-02 at 9 58 00 AM

If I download and run the build here, I don't seem to run into it right away but I did at one point but not sure how to reproduce it yet. Could this be related to the app key issue @beguene? @kyranjamie anything with your work?

**Comment by kyranjamie** [comment]
I'll take a look 🔎

Edit: I can't replicate. Any other details you can share that'd help? If it still happens when you're up, let's jump on a call and go through it.
(Could it back that you were on an older branch, switched to this one, and didn't refresh the background script with the 🔄  in extensions page? 🤔  )

**Comment by fbwoolf** [comment]
> I'll take a look 🔎
> 
> Edit: I can't replicate. Any other details you can share that'd help? If it still happens when you're up, let's jump on a call and go through it. (Could it back that you were on an older branch, switched to this one, and didn't refresh the background script with the 🔄 in extensions page? 🤔 )

@kyranjamie can you run this branch locally > run `yarn clean:all` > `yarn' > 'yarn dev', does that build for you?

**Comment by kyranjamie** [comment]
@fbwoolf it does, yes. I just tried create & restore flows and works fine.

**Comment by fbwoolf** [comment]
> @fbwoolf it does, yes. I just tried create & restore flows and works fine.

Can you remove and reinstall the wallet while local is running then try to create an account, does that work?

**Comment by kyranjamie** [comment]
Removing/reinstalling makes no difference 🤔

**Comment by fbwoolf** [comment]
> Removing/reinstalling makes no difference 🤔

This is so bizarre, I'll dm you in a bit to show you.

**Comment by fbwoolf** [comment]
@beguene @timstackblock curious how your tests go with this build bc I've tried 3 times to get Test 1 to pass from these instructions but each time the salt isn't in localStorage? https://github.com/hirosystems/stacks-wallet-web/pull/2286

Test 2 also fails for me. I'll check the build and keep trying.

**Comment by fbwoolf** [comment]
@beguene can you test the build on this in your AM?  I could not get your app key fix to work today with this build.  Also, I think we need to merge this PR and include it in this release PR to test? https://github.com/hirosystems/stacks-wallet-web/pull/2295

**Comment by andresgalante** [comment]
Good catch @fbwoolf, lets make sure to add #2295 so we have a roll back path

**Comment by beguene** [comment]
Thanks @fbwoolf, I will check it out.

**Comment by beguene** [comment]
@fbwoolf I tested the build and indeed it does not work but my initial PR build did worked. Then I merged Kyran's branch into dev and re-triggered the build. And now it works 🤔 Maybe my previous commit did not trigger a full re-build.
cc: @andresgalante @timstackblock @Eshwari007

**Comment by fbwoolf** [comment]
> @fbwoolf I tested the build and indeed it does not work but my initial PR build did worked. Then I merged Kyran's branch into dev and re-triggered the build. And now it works 🤔 Maybe my previous commit did not trigger a full re-build. cc: @andresgalante @timstackblock @Eshwari007

Great, thanks for double checking it for me. I will test the new build today and make sure it works for me too!

**Comment by beguene** [comment]
@fbwoolf Thanks a lot ! Having you double checking is really valuable 🚀

**Comment by timstackblock** [comment]
@fbwoolf thanks for your feedback I am seeing the salt come in as `undefined` here is a screenshot. I saw this work before the merge, the field was populated with a value now it is not.

Screen Shot 2022-03-15 at 9 52 14 AM

@beguene can you take a look at this issue.

**Review by timstackblock — CHANGES_REQUESTED** [review]
@beguene salt-used-in-app-key-in-gaia = undefined

**Review by timstackblock — APPROVED** [review]

**Review by andresgalante — APPROVED** [review]
QA is ok releasing 🚀  @Eshwari007 @timstackblock 

While QAing this PR we found an issue in the wrap nothing smart contract to investigate later https://github.com/hirosystems/stacks-wallet-web/issues/2301

**Comment by fbwoolf** [comment]
> While QAing this PR we found an issue in the wrap nothing smart contract to investigate later #2301

If this is an error with the `wrapped-nthng` smart contract, why is it reported as an issue in the wallet?

**Comment by Eshwari007** [comment]
> > While QAing this PR we found an issue in the wrap nothing smart contract to investigate later #2301
> 
> If this is an error with the `wrapped-nthng` smart contract, why is it reported as an issue in the wallet?

@fbwoolf I wanted to get our Dev's input in regards to the issue prior to moving it to the concerned repository

**Pull request merged**
