### PR TITLE
Link fixes

### PR DESCRIPTION
**Pull request by RustyF**
fix: removed quotes on markdown links, causing 404 errors

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]

**Comment by kyranjamie** [comment]
Thanks @RustyF 

Edit: The CI is failing, as we follow a commit message standard. If you amend your commit to `fix: readme links`, and do a force push, this check will pass.

**Comment by RustyF** [comment]
Thanks @kyranjamie - I was just trying to amend the commit message after reading up on commit lint!

**Comment by RustyF** [comment]
I've looked at the logs but can't understand what the outstanding problem is.

**Review by hstove — APPROVED** [review]

**Comment by hstove** [comment]
Thanks @RustyF !

**Pull request merged**
