### PR TITLE
feat: masked secret key and added ability to show/hide secret key

### PR DESCRIPTION
**Pull request by Safvan-tsy**
Masked secret key display with * . Provided an option to reveal the value if desired . issue #3560

### CODE REVIEW

**Comment by Safvan-tsy** [comment]
[Screencast from 26-04-23 06:20:09 PM IST.webm](https://user-images.githubusercontent.com/90437519/234783404-215aefbc-cb8a-466d-a39c-8b729e288044.webm)

**Review by kyranjamie — COMMENTED** [review]
Thanks for the contribution @Safvan-tsy

Please amend your commit to follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) standard

@mica000 and @markmhx to review design changes

**Comment by mica000** [comment]
LGTM!

**Comment by kyranjamie** [comment]
@Safvan-tsy, are you able to check the CI jobs, some of them are failing.

Also, let's only use the `react-icons/fi` package, there are similar icons there that are more consistent with the rest of the UI (it also bloats the package so much that the FF build fails).

Suggest running: `yarn lint` to see these too

**Comment by markmhendrickson** [comment]
@Safvan-tsy Do you want to mask the input as well as part of your PR here?

**Comment by Safvan-tsy** [comment]
> @Safvan-tsy, are you able to check the CI jobs, some of them are failing.
> 
> Also, let's only use the `react-icons/fi` package, there are similar icons there that are more consistent with the rest of the UI (it also bloats the package so much that the FF build fails).
> 
> Suggest running: `yarn lint` to see these too

Unfortunately I am travelling. Will definitely check it out.👍

**Comment by Safvan-tsy** [comment]
> @Safvan-tsy Do you want to mask the input as well as part of your PR here?

no

**Comment by Safvan-tsy** [comment]
changed to react-icons/fi

**Comment by fbwoolf** [comment]
@markmhx should this be assigned to me and included with the PR to mask key on sign in?

**Comment by markmhendrickson** [comment]
@fbwoolf this can go live with the other sign in work or released separately, whatever's easiest on your end. I presume it's code complete and just needs rebasing and merge?

**Comment by fbwoolf** [comment]
Closing this in favor of: https://github.com/hirosystems/wallet/pull/3800

**Pull request closed without merging**
