### PR TITLE
feat: new home page with steps

### LINKED ISSUE #1809: Update empty state illustrations for balances and activity
image
image

### LINKED ISSUE #2236: Clicking on the logo redirects to a blank page
During the onboarding, clicking on the Hiro Wallet logo in the header redirects from `chrome-extension://.../index.html#/onboarding` to `chrome-extension://.../index.html#/` which is a blank page, perhaps because the account is not yet authenticated.

https://user-images.githubusercontent.com/239215/153922749-aafd771e-4a25-4201-b535-2264737174d4.mp4

Should clicking on the logo redirect somewhere or we could just remove this interaction? I think it's safe to remove the click interaction in this particular place.

### LINKED ISSUE #2249: Add buy NFT to the onboarding Next steps
As we are wrapping up the onboarding's [Next steps](https://github.com/hirosystems/stacks-wallet-web/pull/2233), we've realized that buying an NFT could be a more attractive next step in the onboarding. Let's explore this change by linking to https://stxnft.com/ perhaps. 

cc/ @eugeniadigon we'll need your help on an illustration!

### LINKED ISSUE #2256: Make new UI layout responsive
Tracking this here for us to go through and ensure all layouts are responsive (and we don't want this to slow us down merging the latest changes). The welcome screen & home page, for example, don't resize down when the viewport is narrowed.

We're mostly there, but some adjustments are needed to make them collapse gracefully. As the narrow viewport styles are needed for the popup, the fullscreen mode should adopt these when narrow. @fbwoolf If you'd find it helpful, let's work on this together.

<details>
<summary>Welcome</summary>

image

</details>

<details>
<summary>Homepage</summary>

Missing padding/horizontal scroll

image

</details>

### LINKED ISSUE #2262: Hiro wallet version overlaps with viewing "Your secret key"
The user notices that Hiro wallet version overlaps with view Your secret key in the full window wallet page
Noticed this in PR : 2259 and also in Prod v3.2.0

Screen Shot 2022-02-23 at 6 38 34 PM

Screen Shot 2022-02-23 at 6 43 36 PM

### LINKED ISSUE #2279: Selecting Hiro wallet header on main page redirects to Backup your secret key page
The user is testing v3.2.0

There are two issues here:

Issue 1:

- User selects the extension
- User views the main onboarding page
- User selects the Hiro wallet header
- User is directed to Backup your secret key page(user was using the account earlier before signing out)

This is a major bug as user had already signed out from the account and selecting the header should not direct user to the previous logged in account secret key

Issue 2:

- User tries to select the header several times to see if its reproducible
- User notices that extension turns to blank screen

Attaching screen recording and screenshot for perusal

https://user-images.githubusercontent.com/38872890/156219101-6136c8a5-e9a1-44a7-95f1-2aff8e06fc45.mov

Screen Shot 2022-03-01 at 12 26 32 PM
Screen Shot 2022-03-01 at 12 27 39 PM

### PR DESCRIPTION
**Pull request by fbwoolf**
> Try out this version of the Hiro Wallet - download [extension builds](https://github.com/hirosystems/stacks-wallet-web/actions/runs/2024077136).

This PR has been opened in place of: https://github.com/hirosystems/stacks-wallet-web/pull/2260

Screen Shot 2022-03-01 at 4 30 51 PM

Responsive:
Screen Shot 2022-03-01 at 4 31 27 PM

cc/ @kyranjamie @landitus

### CODE REVIEW

**Comment by fbwoolf** [comment]
@landitus this should be ready for design review.

**Comment by fbwoolf** [comment]
@kyranjamie those build errors are showing up here now, any thoughts?

EDIT: Nvm, think I figured this out. I had to change our @stacks/network pkg resolution to `3.3.0`.

**Comment by landitus** [comment]
It's looking amazing @fbwoolf !! I have some minor observations:

1. Responsive: The Account name and the action buttons clash while in between the mid-size breakpoints. I would suggest dropping the buttons below when the viewport is 600px or smaller.
2. (Popup size) The next steps titles are missing the external link icon and the whole card should display the legal notice on hover

Next steps - Popup size - 2

Screenshot 2022-03-03 at 20 45 00
Screenshot 2022-03-03 at 20 43 40

**Review by landitus — CHANGES_REQUESTED** [review]
Added feedback

**Comment by fbwoolf** [comment]
@landitus I think we might want to come back to customizing the tooltip when we redesign it across the app? This is how it will look if the card is what triggers the tooltip:

Screen Shot 2022-03-03 at 3 42 58 PM

For reference, our current tooltip uses this library: https://atomiks.github.io/tippyjs/#placements

**Comment by fbwoolf** [comment]
This is when on just the title text, but I think we would need to change the onClick to only be on the title rather than the card:

Screen Shot 2022-03-03 at 3 57 16 PM

**Comment by fbwoolf** [comment]
It seems that our breakpoints are set here so using the array syntax will snap at 768px:
https://github.com/hirosystems/ui/blob/c9efa75863b29b5f30302b38009dded893cf9b0c/packages/ui-theme/src/theme.ts#L26

Screen Shot 2022-03-03 at 4 15 41 PM

**Comment by landitus** [comment]
> It seems that our breakpoints are set here so using the array syntax will snap at 768px:
> 
> https://github.com/hirosystems/ui/blob/c9efa75863b29b5f30302b38009dded893cf9b0c/packages/ui-theme/src/theme.ts#L26
> 
> 
> 
> Screen Shot 2022-03-03 at 4 15 41 PM
> 
> 

Looks good to me! Thank you

**Comment by landitus** [comment]
> This is when on just the title text, but I think we would need to change the onClick to only be on the title rather than the card:
> 
> 
> 
> Screen Shot 2022-03-03 at 3 57 16 PM
> 
>  

Looks good to me as well! I'll add a task to review the tooltip component design for later.

**Comment by fbwoolf** [comment]
@landitus can you remove the change request on this PR if all looks good?

**Review by landitus — APPROVED** [review]
✅ LGTM!

**Comment by fbwoolf** [comment]
@timstackblock @Eshwari007 I moved all the issues linked to this PR into QA. To test the onboarding steps specifically, only a new wallet with 1 account should show the steps. If you create a second account, the steps should hide. Also, if you close the steps they should always remain closed with the current install. The first step should always load as 'Done'. Once a user has STX or an NFT in their account it will mark those steps as done, while just clicking on the step to explore apps will complete that step. Once all 4 steps are done, the onboarding steps section should close. If you sign in with an existing secret key, you should NOT see the steps. Let me know if you have questions. Thx!

**Comment by andresgalante** [comment]
I must be doing something wrong:

- I installed the build on this PR
- I did sign in with my account and then signed out from my account
- Created a new wallet with only 1 account
- I don't see the steps.

What step am I missing?

**Comment by landitus** [comment]
I was re-reviewing this PR as described in https://github.com/hirosystems/stacks-wallet-web/issues/2314 and I found a regression with the layout of the **Accounts list** in the Connect flow (when logging in through a dApp).  Check the video attached where the page is squashed and doesn't expand to the width of the viewport.

https://user-images.githubusercontent.com/239215/159347264-ace9168b-2d16-418e-8bf1-b3bcd0e1e826.mp4

**Comment by fbwoolf** [comment]
> I was re-reviewing this PR as described in #2314 and I found a regression with the layout of the **Accounts list** in the Connect flow (when logging in through a dApp). Check the video attached where the page is squashed and doesn't expand to the width of the viewport.
> 
O yeah, I came across that too at one point and thought I pushed up the fix for it. I'll make sure it gets pushed up, thx!

**Comment by fbwoolf** [comment]
@landitus just confirming I fixed the `Choose an account` page here:

Screen Shot 2022-03-22 at 12 18 47 PM

**Comment by Eshwari007** [comment]
Seems like @andresgalante has a similar issue as me upon install


> I must be doing something wrong:
> 
> * I installed the build on this PR
> * I did sign in with my account and then signed out from my account
> * Created a new wallet with only 1 account
> * I don't see the steps.
> 
> What step am I missing?

**Comment by Eshwari007** [comment]
@landitus @fbwoolf 
Quick question:
https://www.figma.com/file/VupGh90FJtT0dcBj2Sh7bb/%F0%9F%93%90-Old-Spec?node-id=13%3A2418

On this design, I see 'register a name' as one of the selections on the next steps for you
In the current PR ,I do not see it, have we decided to remove the 'register a name' and replace it with 'Buy an NFT'


As per design:

Screen Shot 2022-03-23 at 12 26 30 PM

Current UI view
Screen Shot 2022-03-23 at 12 26 39 PM

**Comment by landitus** [comment]
@Eshwari007 Yes, We've replaced register a name with buy an nft.

**Comment by Eshwari007** [comment]
Believe we can't buy any STX in Testnet hence can remove 'Fund your account'
When the user selects Fund your account in Testnet-user is directed to Transak/Okcoin

https://user-images.githubusercontent.com/38872890/159754302-4e742327-da05-43aa-b505-b10e9c6bf957.mov

cc @fbwoolf @landitus

**Comment by Eshwari007** [comment]
Found an issue -
-When the user creates a new account, the user can see next steps on Account 1
-User switches network  to testnet,user is still able to view the next steps(am not sure if we want to keep these options on testnet as we can't fund the account in testnet)
-User creates Account 2 on testnet, no next steps(all good)
-User switches network to mainnet
-User selects Account 1
-User was not able to view the next steps (shouldn't the user be allowed to view the next steps yet as they have not performed any of the selection yet?)
- Quick question, what if the user wants to buy NFT or explore the apps after closing the next step dialogue? Shouldn't we make it easily retrievable for the user to do so? 


https://user-images.githubusercontent.com/38872890/159756430-2cd1536e-1cb5-4bbb-9887-aab43ef51e88.mov

cc @fbwoolf @landitus

**Comment by fbwoolf** [comment]
> Seems like @andresgalante has a similar issue as me upon install
> 
This scenario is expected. If you sign in with an existing secret key and then create a new account the onboarding steps are already disabled bc we know you already have another account and don't need to onboard again.

**Comment by fbwoolf** [comment]
> Believe we can't buy any STX in Testnet hence can remove 'Fund your account' When the user selects Fund your account in Testnet-user is directed to Transak/Okcoin
> 
The ability to fund your account from the buy page on testnet is not part of these changes. The only change here is adding a link to the buy page from the home page. If the buy page functionality is incorrect then I believe you should just make an issue for it?

**Comment by landitus** [comment]
> User was not able to view the next steps (shouldn't the user be allowed to view the next steps yet as they have not performed any of the selection yet?)

I think the Next steps should be visible as they haven't been completed nor dismissed at that point. Changing to another account or network shouldn't affect the state of the next steps. Wdyt @fbwoolf ?

Regarding if the Next steps should be visible in testnet, I would say to hide it there for the reasons you mentioned. We can improve this later. TBH, we didn't considered this scenario.

Regarding the ability to bring the next steps back after dismissed, this is going to be added later as an improvement.

**Comment by fbwoolf** [comment]
> Found an issue - -When the user creates a new account, the user can see next steps on Account 1 -User switches network to testnet,user is still able to view the next steps(am not sure if we want to keep these options on testnet as we can't fund the account in testnet) -User creates Account 2 on testnet, no next steps(all good) -User switches network to mainnet -User selects Account 1 -User was not able to view the next steps (shouldn't the user be allowed to view the next steps yet as they have not performed any of the selection yet?)
> 
This is all expected behavior, once a second account is created the onboarding steps are disabled. We can enhance the user experience later if needed, but we decided on this implementation as a first iteration.

As for funding with testnet, just having STX in your account will mark the step as `Done`, it doesn't really matter how you get them.
>
> * Quick question, what if the user wants to buy NFT or explore the apps after closing the next step dialogue? Shouldn't we make it easily retrievable for the user to do so?
> 
We have discussed this but it will be an enhancement later.

**Comment by landitus** [comment]
Thanks @fbwoolf! It's all good then. I will create some additional tasks to enhance the experience, which we can tackle later

**Comment by fbwoolf** [comment]
> Thanks @fbwoolf! It's all good then. I will create some additional tasks to enhance the experience, which we can tackle later

Ok great, yeah, the UX isn't perfect by any means but at least it is there to work with and refine. I am going to merge this into dev so I can change the base branch again for the Moonpay work. Thanks @Eshwari007 for testing it.

**Comment by Eshwari007** [comment]
Agree on refining the UX for new home page view.
Adding my findings along the way so that we capture all key points
Notice that when the user hovers over 'Add some funds' there isn't any info dialogue visible though the hand cursor is visible.


https://user-images.githubusercontent.com/38872890/159768672-62a7aa17-1732-41fa-8f4e-02f84cb4fee5.mov

**Comment by Eshwari007** [comment]
cc @markmhx for the findings and info above as well.

**Comment by fbwoolf** [comment]
> Agree on refining the UX for new home page view. Adding my findings along the way so that we capture all key points Notice that when the user hovers over 'Add some funds' there isn't any info dialogue visible though the hand cursor is visible.
> 
This is part of the UI design to distinguish b/w steps that will keep a user in the wallet vs ones that will take a person to an external link. Adding funds keep the user in the wallet while the other two link to external sites to complete the step.

**Pull request merged**
