### PR TITLE
release: psychadelic walrus

### PR DESCRIPTION
**Pull request by pete-watters**
> _Building Leather at commit ea76352_

This release contains fixes for: 
- https://github.com/leather-io/extension/issues/5739
- https://github.com/leather-io/extension/issues/5756
- https://github.com/leather-io/extension/issues/5735
- https://github.com/leather-io/issues/issues/227
- https://github.com/leather-io/issues/issues/249
- https://github.com/leather-io/extension/issues/5260
- https://github.com/leather-io/issues/issues/235
- https://github.com/leather-io/extension/issues/5248
- https://github.com/leather-io/extension/issues/4714
- https://github.com/leather-io/extension/issues/3631
- https://github.com/leather-io/extension/issues/5755
- https://github.com/leather-io/extension/issues/4597
- https://github.com/leather-io/extension/issues/5777
- https://github.com/leather-io/extension/issues/5734
- https://github.com/leather-io/extension/issues/5802

It also includes:
- CI updates
- Monorepo package dependancy updates 
- Test updates
- Clearing some console errors

Other PRs:
- https://github.com/leather-io/extension/pull/5776

### CODE REVIEW

**Comment by pete-watters** [comment]
@fbwoolf @alter-eggo @edgarkhanzadian: 

This release should also contain some package updates https://github.com/leather-io/extension/pull/5793. For the UI library update there is a breaking change that needs to first merge this https://github.com/leather-io/extension/pull/5796 

It would be great if we could also include https://github.com/leather-io/extension/pull/5785

**Comment by fbwoolf** [comment]
> @fbwoolf @alter-eggo @edgarkhanzadian:
> 
> This release should also contain some package updates #5793. For the UI library update there is a breaking change that needs to first merge this #5796
> 
> It would be great if we could also include #5785

Once these are all merged here, I can test the build and approve.

**Comment by pete-watters** [comment]
> > @fbwoolf @alter-eggo @edgarkhanzadian:
> > This release should also contain some package updates #5793. For the UI library update there is a breaking change that needs to first merge this #5796
> > It would be great if we could also include #5785
> 
> Once these are all merged here, I can test the build and approve.

Thanks @fbwoolf 👍 The last outstanding PR is this one to manually update the packages as the bot PR failed https://github.com/leather-io/extension/pull/5799

**Comment by fbwoolf** [comment]
I tested the build here and seems good, are the alignment issues in the header captured in an issue somewhere? The `Leather` logo is off at times to the left, while the menu icon is sometimes out of alignment on the right. I do see this in production though too...

Screenshot 2024-08-21 at 7 36 02 PM

Screenshot 2024-08-21 at 7 36 47 PM

**Review by fbwoolf — APPROVED** [review]

**Comment by pete-watters** [comment]
> I tested the build here and seems good, are the alignment issues in the header captured in an issue somewhere? The `Leather` logo is off at times to the left, while the menu icon is sometimes out of alignment on the right. I do see this in production though too...
> 
> Screenshot 2024-08-21 at 7 36 02 PM Screenshot 2024-08-21 at 7 36 47 PM

Thanks @fbwoolf. I think that's a follow on bug from the previous release that's not captured anywhere. Let me take a look at that now in case it's something I can fix quickly and include here.

I opened a bug for it https://github.com/leather-io/extension/issues/5802 and have a draft PR https://github.com/leather-io/extension/pull/5801

**Review by alter-eggo — APPROVED** [review]

**Pull request merged**
