### PR TITLE
fix: better handling for mobile and blocked popups

### PR DESCRIPTION
**Pull request by hstove**
Fixes for #300 and #333

### CODE REVIEW

**Review by kyranjamie — APPROVED** [review]

**Comment by hstove** [comment]
@timstackblock the Netlify build should be fixed here. I think there were some API errors on the Netlify when this tried to deploy the first time. It's working now.

**Comment by timstackblock** [comment]
Found a weird bug here http://somup.com/cYhI25jrBU its not a show stopper because I can get around it if I just close out and do it again. But we should definitely fix it to make the roll out go smoothly.

If I select "I already have a secret key" by accident then close that box and select the option to "generate a new secret key" the box opens back up and prompts me to enter the 12 word seed phrase again.

**Comment by hstove** [comment]
Thanks @timstackblock - we are tracking that bug in #381 . Let's try and QA this ticket regardless of that bug

**Comment by markmhendrickson** [comment]
@hstove to merge

**Pull request merged**
